-- Truncate the person OBSERVATIONS after a normalizer change.
--
-- ⚠️ THIS IS ONE HALF OF THE CEREMONY. The canonical tier keyed to these
-- observations — `canonical_person`, the identity links, the junctions, the
-- tenures — and the sponsor/underwriter families are a downstream package's,
-- each with its own script. Run them together, or the survivors of one point at
-- rows the other deleted: a canonical row whose observations are gone resolves
-- nothing, and an observation whose link survives makes every later rebuild
-- raise.
--
-- Why this exists instead of a resolver version bump: a version bump is the
-- ceremony for changing a normalizer while KEEPING the rows minted under the
-- old one, so the two generations can be compared and rolled between. When the
-- old rows are disposable, wiping them is both cheaper and more honest — there
-- is no "previous" worth preserving, and leaving one behind would make
-- `version coverage` report against a generation nobody intends to keep.
--
-- What is stale, and therefore what is here:
--
--   * `person_observations.normalized_*` and every `person_hash_id` derived
--     from one. `normalizePerson` folds accents into the IDENTITY parts, so
--     each of those values is computed differently — and no SQL can recompute
--     them, because the fold is TypeScript on the extraction path. The person
--     canonical tier keyed on them is a downstream package's, wiped by its
--     paired script — see the ⚠️ above.
--
-- The COMPANY canonical tier is NOT wiped by either half — but it is NOT
-- untouched either, and that difference is why step 3b below is mandatory.
--
-- `normalizeCompanyName` DID change in this same release, so
-- `company_observations.normalized_name` — the column `canonical_company` is
-- keyed on, and the one `CompanyResolver`'s name fallback matches against — is
-- stale for every observation the new rules key differently. Three real
-- before/after pairs:
--
--   Churchill Capital Corp I        "Churchill Capital"             → "Churchill Capital Corp I"
--   Reinvent Technology Partners Y  "Reinvent Technology Partners"  → stays distinct from the plain name
--   Blue Acquisition Corp/Cayman    unchanged (kept "/Cayman")      → "Blue Acquisition"
--
-- The first two are the point of the release: a placeholder suffix
-- interpolated into a `RegExp` was read as a character class and deleted
-- single-letter words, so `Churchill Capital Corp I` collided with plain
-- `Churchill Capital`, and the two unrelated filers `Reinvent Technology
-- Partners` (CIK 1819848) and `Reinvent Technology Partners Y` (CIK 1828108)
-- shared ONE canonical identity.
--
-- Those rows are stale but they are also REBUILDABLE, which is exactly why
-- wiping is the wrong tool here: `normalized_name` is derived from the `name`
-- every company observation already carries, so one command recomputes it in
-- place — no re-extraction, no AI cost. The command belongs to the package that
-- owns the canonical tier, and its paired script prescribes it as step 3 — but
-- it is written out here too, because an operator reading this file is the one
-- about to skip it:
--
--   resolve --kind company --all --renormalize
--
-- ⚠️ THAT PASS IS REQUIRED, not optional, and nothing errors if you skip it.
-- The stale keys keep resolving, `version coverage` keeps reporting full
-- coverage, and the merged canonical identities this release exists to SPLIT
-- survive silently. It runs after the backfills below and before the alias
-- imports — aliases are matched by canonical DISPLAY NAME, so they must be
-- imported against the re-resolved tier.
--
-- Expected residue afterwards: `canonical_company` rows minted under the
-- PREVIOUS normalized names survive the re-partition with zero identity links
-- pointing at them. They are inert, not corruption — nothing reads a canonical
-- row no link cites — and they are left in place because removing them needs a
-- reachability sweep this ceremony does not do. The visible fallout is
-- aliases: one whose target was such a row now points at an orphan, which the
-- downstream `canonical company alias-list --orphans` lists.
--
-- (`generateCompanyHash` does fold diacritics where `normalizeCompanyName`
-- does not, but no table stores `company_hash_id`; it is a derived slug, not
-- the company identity key, so it is no part of this.)
--
-- `observation_provenance` is scoped to `kind = 'person'` for the same reason.
-- Its person rows cannot outlive the person observations they cite; its
-- company rows cite company observations that survive.
--
-- What is deliberately NOT truncated: raw EDGAR ingest — `entities`,
-- `filings`, `cik_names`, `company_facts`, `xbrl_fact`, `processed_*`, and the
-- `spac`/`spac_deal`/`spac_event` lifecycle. None of it is keyed by a
-- normalizer, and re-downloading it costs hours against a rate limit.
--
-- ⚠️ EXPORT YOUR ALIASES FIRST — before running either half. No alias table is
-- in this script any more, but the paired one destroys them: they are
-- hand-curated claims that two canonical rows are one entity, keyed by
-- canonical UUIDs that script wipes. Its header carries the export commands.
--
-- Usage (SQLite):
--   sqlite3 "$SEC_DB_FOLDER/$SEC_DB_NAME.sqlite" < scripts/sql/truncate-identity-tier.sql
--
-- ⚠️ On Postgres use `scripts/sql/truncate-identity-tier.postgres.sql` instead.
-- The names below are UNQUALIFIED, so on a deployment whose `search_path` lists
-- a staging or shared schema first they would resolve into the WRONG schema and
-- delete that one's identity tier irreversibly. The Postgres variant pins
-- `search_path` to `current_schema()`; that statement is not portable (sqlite3
-- rejects it) and portability is this file's only reason to exist, so the two
-- stay separate rather than one growing a dialect-specific line.
--
-- Then, in this order:
--
-- 3a. Re-extract every extractor whose output this script deleted (see
--     REKEY_REEXTRACT_EXTRACTOR_IDS) — the person-observing ones exactly.
--     `424` is not among them: it observes no person, and the tier it does
--     write for is re-keyed by its own script with its own gate list.
--   sec extractor backfill S-1
--   sec extractor backfill D
--   sec extractor backfill C
--   sec extractor backfill CFPORTAL
--   sec extractor backfill 1-A
--   sec extractor backfill 1-Z
--   sec extractor backfill 3
--   sec extractor backfill 4
--   sec extractor backfill 5
--   sec extractor backfill 144
--
-- 3b. Re-resolve, re-key the COMPANY tier, and re-import the aliases — all of
--     it from the paired script's header, because all of it is that package's
--     surface now. Its step 3 is the mandatory company recompute this file's
--     COMPANY paragraph above explains; skipping it is silent, and the merged
--     canonical identities the ceremony exists to split survive.
--
-- DELETE rather than TRUNCATE: SQLite has no TRUNCATE, and `DELETE FROM` with
-- no WHERE is its optimized whole-table delete. On Postgres this is slower than
-- TRUNCATE but avoids the ACCESS EXCLUSIVE lock, and these tables are small.

BEGIN;

-- ── Person observations, and everything keyed to one ─────────────────────────
-- These carry `observation_id` FKs, so they cannot outlive the observations.
-- `observation_provenance` is shared with the company tier, whose observations
-- survive — hence the WHERE.
DELETE FROM beneficial_ownership;
DELETE FROM executive_compensation;
DELETE FROM related_party_transactions;
DELETE FROM observation_provenance WHERE kind = 'person';
DELETE FROM person_observation_titles;
DELETE FROM person_observations;

-- ── Re-extraction gates ──────────────────────────────────────────────────────
-- Last, and the reason no version bump is needed: the forms sweep selects
-- filings by anti-joining `extractor_runs` at the active version, so clearing a
-- row makes that filing unprocessed again at the SAME version. Dead letters go
-- with it — they are keyed to runs that no longer exist.
--
-- Scoped to the extractors whose output this script actually deletes: the
-- person-observing ones exactly. `424` is NOT here — it writes family link rows
-- and no person observation, and the package owning that tier gates it from its
-- own script. Clearing its runs from here would re-extract every priced
-- prospectus on a deployment whose family tier this script never touched.
-- `8-K`, `merger-proxy`, `redemption` and `loi` stay out for the same reason:
-- nothing of theirs is deleted here. Keep in step with REKEY_REEXTRACT_EXTRACTOR_IDS
-- in `src/storage/versioning/extractorIds.ts` — `truncateIdentityTier.test.ts`
-- fails if they diverge.
DELETE FROM extraction_dead_letter
WHERE extractor_id IN ('D', 'C', 'CFPORTAL', '1-A', '1-Z', '3', '4', '5', '144', 'S-1');
DELETE FROM extractor_runs
WHERE extractor_id IN ('D', 'C', 'CFPORTAL', '1-A', '1-Z', '3', '4', '5', '144', 'S-1');

COMMIT;
