/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import { describe, expect, it } from "vitest";
import { ALL_FORMS_MAP, isFormParsingSupported } from "../../sec/forms/all-forms";
import { Form_DRS } from "../../sec/forms/registration-statements/Form_DRS";
import { Form_DRSLTR } from "../../sec/forms/registration-statements/Form_DRSLTR";
import {
  allRegisteredForms,
  extractorIdsForForm,
  formsForExtractorIds,
} from "../../sec/forms/formExtractors";
import { registerSecFormExtractors } from "../../config/registerFormExtractors";
import { EXTRACTOR_IDS, isNonfatalTimelineExtractor } from "./extractorIds";

// Every routing assertion below answers from the form-extractor registry, which
// is empty until something registers into it.
registerSecFormExtractors();

/**
 * The extractor ids `form` routes to. Routing is a SET — a form may carry
 * several extractors — so each assertion below asks about membership rather
 * than about equality with whichever one happens to be first.
 */
function routedIds(form: string): readonly string[] {
  return extractorIdsForForm(form);
}

/** Asserts `form` routes to `id`, and that it routes anywhere at all. */
function expectRoutedTo(form: string, id: string): void {
  const ids = routedIds(form);
  expect(ids, `form ${form}`).not.toHaveLength(0);
  expect(ids, `form ${form}`).toContain(id);
}

describe("extractorIds", () => {
  it("exposes the canonical extractor ids", () => {
    expect([...EXTRACTOR_IDS].sort()).toEqual([
      "1-A",
      "1-A-W",
      "1-K",
      "1-SA",
      "1-U",
      "1-Z",
      "144",
      "25-15",
      "253G",
      "3",
      "4",
      "424",
      "5",
      "8-K",
      "C",
      "CFPORTAL",
      "D",
      "QUALIF",
      "RW",
      "S-1",
      "loi",
      "merger-proxy",
      "redemption",
    ]);
  });

  it("treats ownership forms as nonfatal on the SPAC timeline", () => {
    for (const form of ["3", "3/A", "4", "4/A", "5", "5/A", "144", "144/A"]) {
      const ids = routedIds(form);
      expect(ids, `form ${form}`).not.toHaveLength(0);
      for (const id of ids) {
        expect(isNonfatalTimelineExtractor(id), `${form} routes to ${id}`).toBe(true);
      }
    }
    expect(isNonfatalTimelineExtractor("D")).toBe(false);
    expect(isNonfatalTimelineExtractor("S-1")).toBe(false);
  });

  it("maps the merger proxies to extractor id 'merger-proxy'", () => {
    for (const form of ["DEFM14A", "PREM14A", "DEFM14C", "PREM14C", "DEFR14A", "PRER14A"]) {
      expectRoutedTo(form, "merger-proxy");
    }
  });

  it("maps the 424 prospectus variants to extractor id '424'", () => {
    for (const form of ["424A", "424B1", "424B2", "424B3", "424B4", "424B5", "424B7"]) {
      expectRoutedTo(form, "424");
    }
  });

  it("maps Form 3/4/5 and amendments to their document-type extractor ids", () => {
    for (const form of ["3", "4", "5"]) {
      expectRoutedTo(form, form);
      expectRoutedTo(`${form}/A`, form);
    }
  });

  it("maps Form 144 and its amendment to extractor id '144'", () => {
    expectRoutedTo("144", "144");
    expectRoutedTo("144/A", "144");
  });

  it("maps Form D and amendments to extractor id 'D'", () => {
    expectRoutedTo("D", "D");
    expectRoutedTo("D/A", "D");
  });

  it("maps every Form C variant to extractor id 'C'", () => {
    for (const v of [
      "C",
      "C/A",
      "C-W",
      "C-U",
      "C-U-W",
      "C/A-W",
      "C-AR",
      "C-AR-W",
      "C-AR/A",
      "C-AR/A-W",
      "C-TR",
      "C-TR-W",
    ]) {
      expectRoutedTo(v, "C");
    }
  });

  it("maps Form 1-A and amendments to extractor id '1-A'", () => {
    expectRoutedTo("1-A", "1-A");
    expectRoutedTo("1-A/A", "1-A");
  });

  it("maps Form 1-K and amendments to extractor id '1-K'", () => {
    expectRoutedTo("1-K", "1-K");
    expectRoutedTo("1-K/A", "1-K");
  });

  it("maps Form 1-U and amendments to extractor id '1-U'", () => {
    // Metadata-only, like 25-15: the item codes arrive in the submissions
    // payload, so the event is known without reading the narrative body.
    expectRoutedTo("1-U", "1-U");
    expectRoutedTo("1-U/A", "1-U");
  });

  it("maps the SEC's QUALIF notice to its own extractor id", () => {
    // Its own id rather than folding into "1-A": QUALIF is generated by the
    // Commission, not the filer, and carries the authoritative qualification
    // date. Sharing an id would make a version bump for one re-run the other.
    expectRoutedTo("QUALIF", "QUALIF");
  });

  it("maps Form 1-Z and amendments to extractor id '1-Z'", () => {
    expectRoutedTo("1-Z", "1-Z");
    expectRoutedTo("1-Z/A", "1-Z");
  });

  it("routes an unknown form nowhere", () => {
    expect(routedIds("10-K")).toEqual([]);
    expect(routedIds("")).toEqual([]);
  });

  it("routes the amendment and withdrawal variants, not just the base symbols", () => {
    const registered = new Set(allRegisteredForms());
    expect(registered.has("D/A")).toBe(true);
    expect(registered.has("C-AR/A-W")).toBe(true);
    expect(registered.has("1-Z/A")).toBe(true);
  });
});

describe("extractorIds — S-1", () => {
  it("includes S-1 in the registry", () => {
    expect(EXTRACTOR_IDS).toContain("S-1");
  });

  it("maps S-1 form symbols to the S-1 extractor", () => {
    expectRoutedTo("S-1", "S-1");
    expectRoutedTo("S-1/A", "S-1");
    expectRoutedTo("S-1MEF", "S-1");
  });
});

describe("extractorIds + ALL_FORMS_MAP invariant", () => {
  it("every form an extractor is registered for is registered in ALL_FORMS_MAP", () => {
    const missing: string[] = [];
    for (const form of allRegisteredForms()) {
      if (!ALL_FORMS_MAP.has(form)) {
        missing.push(form);
      }
    }
    expect(missing).toEqual([]);
  });
});

describe("extractorIds — DRS dispatch mapping", () => {
  it("maps DRS and DRS/A to the S-1 extractor and leaves DRSLTR unmapped", () => {
    expectRoutedTo("DRS", "S-1");
    expectRoutedTo("DRS/A", "S-1");
    expect(routedIds("DRSLTR")).toEqual([]);
  });
});

describe("extractorIds — SEC STAFF ACTION withdrawal dispatch", () => {
  it("routes SEC STAFF ACTION to RW and leaves EFFECT / SEC ACTION unmapped", () => {
    // Staff action is not Form RW, but a last-word staff action on an
    // unpriced registration is the same lifecycle end. processWithdrawal
    // still no-ops when a later S-1 exists (Iron Horse). EFFECT and SEC ACTION
    // are unrelated codes.
    expectRoutedTo("SEC STAFF ACTION", "RW");
    expect(isFormParsingSupported("SEC STAFF ACTION")).toBe(true);
    expect(routedIds("EFFECT")).toEqual([]);
    expect(routedIds("SEC ACTION")).toEqual([]);
  });
});

describe("extractorIds — Form RW registration-withdrawal dispatch mapping", () => {
  it("maps Form RW to extractor id 'RW' and does not route RW WD", () => {
    expectRoutedTo("RW", "RW");
    expect(routedIds("RW WD")).toEqual([]);
  });
});

describe("extractorIds — Form 25/15 deregistration dispatch mapping", () => {
  it("maps Form 25 / 25-NSE and the Form 15 family to extractor id '25-15'", () => {
    for (const form of [
      "25",
      "25/A",
      "25-NSE",
      "25-NSE/A",
      "15-12B",
      "15-12B/A",
      "15-12G",
      "15-12G/A",
      "15-15D",
      "15-15D/A",
      "15F-12B",
      "15F-12B/A",
      "15F-12G",
      "15F-12G/A",
      "15F-15D",
      "15F-15D/A",
      "20-F",
      "20-F/A",
    ]) {
      expectRoutedTo(form, "25-15");
    }
  });
});

describe("extractorIds — F-1 (foreign issuer) dispatch mapping", () => {
  it("maps F-1, F-1/A, and F-1MEF to the S-1 extractor", () => {
    expectRoutedTo("F-1", "S-1");
    expectRoutedTo("F-1/A", "S-1");
    expectRoutedTo("F-1MEF", "S-1");
  });
});

describe("Form_DRS — DRSLTR catalogued separately, never extracted", () => {
  it("Form_DRS.forms does not include DRSLTR (correspondence letter, not a prospectus)", () => {
    expect(Form_DRS.forms).not.toContain("DRSLTR");
  });
  it("DRSLTR is described by its own Form class, not the prospectus one", () => {
    expect(ALL_FORMS_MAP.get("DRSLTR")).toBe(Form_DRSLTR);
  });
  it("being catalogued does not route DRSLTR to an extractor", () => {
    expect(routedIds("DRSLTR")).toEqual([]);
    expect(isFormParsingSupported("DRSLTR")).toBe(false);
  });
});

describe("formsForExtractorIds", () => {
  it("returns every form mapped to a requested extractor id", () => {
    const forms = formsForExtractorIds(["D"]);

    expect(forms).toContain("D");
    expect(forms).toContain("D/A");
    expect(forms.every((form) => routedIds(form).includes("D"))).toBe(true);
  });

  it("returns forms for multiple extractor ids", () => {
    const forms = formsForExtractorIds(["CFPORTAL", "C"]);
    const extractors = new Set(forms.flatMap((form) => routedIds(form)));

    expect(extractors).toEqual(new Set(["CFPORTAL", "C"]));
  });

  it("returns an empty list when no extractor ids match", () => {
    expect(formsForExtractorIds([])).toEqual([]);
  });
});
