// Code generated by xgen. DO NOT EDIT.

// The schema version element applies only to the submission's primary document. It does not apply to the submission file. This element should not be included in a Reduced Content submission. EDGAR inserts this element in the version of the primary document that gets disseminated. If you do provide a value for this element and it does not match the current version of this schemafile being used by EDGAR, then EDGAR will generate a WARNING.
export type SCHEMA_VERSION_TYPE = string;

// NEW_FILE_NUM_TYPE ...
export type NEW_FILE_NUM_TYPE = "NEW";

// TRUE_FALSE_TYPE ...
export type TRUE_FALSE_TYPE = boolean;

// RELATED_FORM_TYPE ...
export enum RELATED_FORM_TYPE {
  "10-D" = "10-D",
  "10-D/A" = "10-D/A",
  "ABS-EE" = "ABS-EE",
  "ABS-EE/A" = "ABS-EE/A",
}

// ACCELERATED_STATUS_TYPE ...
export type ACCELERATED_STATUS_TYPE =
  | "Non-Accelerated Filer"
  | "Accelerated Filer"
  | "Large Accelerated Filer"
  | "Not Applicable";

// SEC supplied CIK for the Filer. Enter up to 10 numeric characters. When fewer than 10 characters are entered, the field will be pre filled with zeroes.
export type CIK_TYPE = string;

// DATE_TYPE ...
export type DATE_TYPE = string;

// For MM/DD/YYYY date format
export type DATE_TYPE2 = string;

// Your CIK confirmation code [CCC]. Field is 8 characters, at least one of which must be a numeral and at least one must be a @, #, $, or *; case-sensitive.
export type CCC_TYPE = string;

// Valid prefixes for this submission type are 002-, 033-, and 333-.
export type FILE_NUMBER_TYPE = string;

export type INTEGER_TYPE_10 = number;

// The prefix may contain 1-3 digits, the sequence number may contain 1-8 digits, the optional suffix may contain 1-4 characters, and the fields are separated with a hyphen. Sample value: 333-00000-1.
export interface FILE_NUMBER_TYPE_2 {
  NEW_FILE_NUM_TYPE: string;
  FILE_NUMBER_TYPE: string;
}

// DEPOSITOR_TYPE ...
export interface DEPOSITOR_TYPE {
  depositorId: string;
  depositorFileNumber: string;
}

// SUCCESSOR_TYPE ...
export interface SUCCESSOR_TYPE {
  successorFilingFlag: string;
  successorFileNumber: string;
}

// A Company Name can be up to 150 characters.
export type ENTITY_NAME_TYPE = string;

// A Company Name can be up to 256 characters.
export type ENTITY_NAME_TYPE_256 = string;

// New EDGAR contact Internet identification. Field must be in standard Internet address format, including exactly one "@" character, at least one "." after the "@", one or more EDGAR acceptable characters before the "@" and one or more acceptable EDGAR characters before and after each existing "." Address may be up to 80 characters long.
export type INTERNET_ADDRESS_TYPE = string;

// Identifies the investment company type of the acquiring company. Choose a value from the list displayed when the arrow is selected.
export type INV_COMPANY_TYPE =
  | "N-1A"
  | "N-1"
  | "N-2"
  | "N-3"
  | "N-4"
  | "N-5"
  | "N-6"
  | "S-1 or S-3"
  | "S-6"
  | "OTHER";

// Marks submission to be treated as a LIVE filing.Unless the "TEST" button is selected, the filing will be treated by EDGAR as a live filing and, if accepted, be disseminated. Submit live filings in LIVE mode if using EDGARLink Online. A filing with TEST selected cannot be changed into a live filing.
export type LIVE_TEST_TYPE = "LIVE" | "TEST";

// RPT_OWNER_RELATIONSHIP_TYPE ...
export type RPT_OWNER_RELATIONSHIP_TYPE = "DIRECTOR" | "OFFICER" | "OWNER" | "OTHER";

// US_STATE_CODES ...
export type US_STATE_CODES =
  | "AL"
  | "AK"
  | "AZ"
  | "AR"
  | "CA"
  | "CO"
  | "CT"
  | "DE"
  | "DC"
  | "FL"
  | "GA"
  | "HI"
  | "ID"
  | "IL"
  | "IN"
  | "IA"
  | "KS"
  | "KY"
  | "LA"
  | "ME"
  | "MD"
  | "MA"
  | "MI"
  | "MN"
  | "MS"
  | "MO"
  | "MT"
  | "NE"
  | "NV"
  | "NH"
  | "NJ"
  | "NM"
  | "NY"
  | "NC"
  | "ND"
  | "OH"
  | "OK"
  | "OR"
  | "PA"
  | "RI"
  | "SC"
  | "SD"
  | "TN"
  | "TX"
  | "UT"
  | "VT"
  | "VA"
  | "WA"
  | "WV"
  | "WI"
  | "WY"
  | "PR"
  | "VI";

export type US_STATE_CODES_AND_TERRITORIES =
  | "AL"
  | "AK"
  | "AZ"
  | "AR"
  | "CA"
  | "CO"
  | "CT"
  | "DE"
  | "DC"
  | "FL"
  | "GA"
  | "GU"
  | "HI"
  | "ID"
  | "IL"
  | "IN"
  | "IA"
  | "KS"
  | "KY"
  | "LA"
  | "ME"
  | "MD"
  | "MA"
  | "MI"
  | "MN"
  | "MS"
  | "MO"
  | "MT"
  | "NE"
  | "NV"
  | "NH"
  | "NJ"
  | "NM"
  | "NY"
  | "NC"
  | "ND"
  | "OH"
  | "OK"
  | "OR"
  | "PA"
  | "PR"
  | "RI"
  | "SC"
  | "SD"
  | "TN"
  | "TX"
  | "UT"
  | "VT"
  | "VI"
  | "VA"
  | "WA"
  | "WV"
  | "WI"
  | "WY"
  | "B5"
  | "1V";

// Set of Country Codes (excluding US) according to EDGAR
export type NON_US_COUNTRY_CODES =
  | "A0"
  | "A1"
  | "A2"
  | "A3"
  | "A4"
  | "A5"
  | "A6"
  | "A7"
  | "A8"
  | "A9"
  | "B0"
  | "Z4"
  | "B2"
  | "Y6"
  | "B3"
  | "B4"
  | "B5"
  | "B6"
  | "B7"
  | "1A"
  | "B8"
  | "B9"
  | "C1"
  | "1B"
  | "1C"
  | "C3"
  | "C4"
  | "1D"
  | "C5"
  | "C6"
  | "C7"
  | "C8"
  | "1F"
  | "C9"
  | "D1"
  | "G6"
  | "D0"
  | "D2"
  | "D3"
  | "1E"
  | "B1"
  | "D4"
  | "D5"
  | "D6"
  | "D9"
  | "E0"
  | "X2"
  | "E2"
  | "E3"
  | "E4"
  | "E8"
  | "E9"
  | "F0"
  | "F2"
  | "F3"
  | "F4"
  | "F6"
  | "F7"
  | "F8"
  | "F9"
  | "G0"
  | "Y3"
  | "G1"
  | "G2"
  | "L7"
  | "1M"
  | "G3"
  | "G4"
  | "2N"
  | "G7"
  | "1G"
  | "G9"
  | "G8"
  | "H1"
  | "H2"
  | "H3"
  | "H4"
  | "1J"
  | "1H"
  | "H5"
  | "H7"
  | "H6"
  | "H8"
  | "H9"
  | "I0"
  | "I3"
  | "I4"
  | "2C"
  | "I5"
  | "I6"
  | "2Q"
  | "2M"
  | "J0"
  | "J1"
  | "J3"
  | "J4"
  | "J5"
  | "J6"
  | "GU"
  | "J8"
  | "Y7"
  | "J9"
  | "S0"
  | "K0"
  | "K1"
  | "K4"
  | "X4"
  | "K2"
  | "K3"
  | "K5"
  | "K6"
  | "K7"
  | "K8"
  | "K9"
  | "L0"
  | "L2"
  | "Y8"
  | "L3"
  | "L6"
  | "L8"
  | "M0"
  | "Y9"
  | "M2"
  | "1P"
  | "M3"
  | "J2"
  | "M4"
  | "M5"
  | "M6"
  | "1N"
  | "M7"
  | "1R"
  | "M8"
  | "M9"
  | "N0"
  | "N1"
  | "N2"
  | "1Q"
  | "N4"
  | "N5"
  | "1U"
  | "N6"
  | "N7"
  | "N8"
  | "N9"
  | "O0"
  | "O1"
  | "1T"
  | "O2"
  | "O3"
  | "O4"
  | "2P"
  | "O5"
  | "1K"
  | "1S"
  | "O9"
  | "P0"
  | "Z5"
  | "P1"
  | "P2"
  | "P3"
  | "E1"
  | "T6"
  | "P5"
  | "P6"
  | "P7"
  | "P8"
  | "1W"
  | "Q2"
  | "Q3"
  | "Q4"
  | "Q5"
  | "Q6"
  | "Q7"
  | "1V"
  | "Q8"
  | "P4"
  | "R0"
  | "1Y"
  | "1X"
  | "R1"
  | "R2"
  | "R4"
  | "R5"
  | "R6"
  | "R8"
  | "R9"
  | "S1"
  | "S3"
  | "S4"
  | "S5"
  | "1Z"
  | "S6"
  | "Z0"
  | "U8"
  | "U7"
  | "U9"
  | "Z1"
  | "V0"
  | "V1"
  | "Y0"
  | "S8"
  | "S9"
  | "T0"
  | "T1"
  | "Z2"
  | "T2"
  | "T8"
  | "U0"
  | "2B"
  | "2A"
  | "D7"
  | "U1"
  | "T3"
  | "1L"
  | "U3"
  | "F1"
  | "V2"
  | "V3"
  | "L9"
  | "V6"
  | "V7"
  | "V8"
  | "V9"
  | "F5"
  | "2D"
  | "W0"
  | "W1"
  | "Z3"
  | "W2"
  | "W3"
  | "W4"
  | "W5"
  | "W6"
  | "W8"
  | "2E"
  | "W7"
  | "2G"
  | "W9"
  | "2H"
  | "C0"
  | "X0"
  | "2J"
  | "X3"
  | "2K"
  | "2L"
  | "X5"
  | "Q1"
  | "D8"
  | "X8"
  | "U5"
  | "T7"
  | "Y4"
  | "Y5"
  | "XX"
  | "C2"
  | "E5"
  | "E7"
  | "G5"
  | "I7"
  | "X9"
  | "I8"
  | "I9"
  | "L1"
  | "L4"
  | "L5"
  | "M1"
  | "O6"
  | "Q9"
  | "R3"
  | "T4"
  | "U2"
  | "U4"
  | "U6"
  | "X7"
  | "2F"
  | "Y2";

// Type of submission you are filing. Choose a value from the appropriate family of Submission Types.
export type SUBMISSION_TYPE =
  | "10-12B"
  | "10-12B/A"
  | "10-12G"
  | "10-12G/A"
  | "10-D"
  | "10-D/A"
  | "10-K"
  | "10-K/A"
  | "10KSB"
  | "10KSB/A"
  | "10-KT"
  | "10-KT/A"
  | "10-Q"
  | "10-Q/A"
  | "10-QT"
  | "10-QT/A"
  | "11-K"
  | "11-K/A"
  | "11-KT"
  | "11-KT/A"
  | "13H"
  | "13H-A"
  | "13H-I"
  | "13H-R"
  | "13H/A"
  | "13H-T"
  | "144"
  | "144/A"
  | "15-12B"
  | "15-12B/A"
  | "15-12G"
  | "15-12G/A"
  | "15-15D"
  | "15-15D/A"
  | "15F-12B"
  | "15F-12B/A"
  | "15F-12G"
  | "15F-12G/A"
  | "15F-15D"
  | "15F-15D/A"
  | "18-12B"
  | "18-12B/A"
  | "18-12G"
  | "18-12G/A"
  | "18-K"
  | "18-K/A"
  | "1-E AD"
  | "1-E AD/A"
  | "1-E"
  | "1-E/A"
  | "20-F"
  | "20-F/A"
  | "20FR12B"
  | "20FR12B/A"
  | "20FR12G"
  | "20FR12G/A"
  | "24F-2NT"
  | "24F-2NT/A"
  | "25"
  | "25/A"
  | "2-E"
  | "2-E/A"
  | "305B2"
  | "305B2/A"
  | "40-17F1"
  | "40-17F1/A"
  | "40-17F2"
  | "40-17F2/A"
  | "40-17G"
  | "40-17G/A"
  | "40-17GCS"
  | "40-17GCS/A"
  | "40-24B2"
  | "40-24B2/A"
  | "40-33"
  | "40-33/A"
  | "40-6B"
  | "40-6B/A"
  | "40-8B25"
  | "40-8F-2"
  | "40-8F-2/A"
  | "40-APP"
  | "40-APP/A"
  | "40-F"
  | "40-F/A"
  | "40FR12B"
  | "40FR12B/A"
  | "40FR12G"
  | "40FR12G/A"
  | "40-OIP"
  | "40-OIP/A"
  | "424A"
  | "424B1"
  | "424B2"
  | "424B3"
  | "424B4"
  | "424B5"
  | "424B7"
  | "424B8"
  | "424H"
  | "424H/A"
  | "424I"
  | "425"
  | "485APOS"
  | "485BPOS"
  | "485BXT"
  | "486APOS"
  | "486BPOS"
  | "486BXT"
  | "487"
  | "497"
  | "497AD"
  | "497H2"
  | "497J"
  | "497K1"
  | "497K2"
  | "497K3A"
  | "497K3B"
  | "6-K"
  | "6-K/A"
  | "8-A12B"
  | "8-A12B/A"
  | "8-A12G"
  | "8-A12G/A"
  | "8-K"
  | "8-K/A"
  | "8-K12B"
  | "8-K12B/A"
  | "8-K12G3"
  | "8-K12G3/A"
  | "8-K15D5"
  | "8-K15D5/A"
  | "ABS-15G"
  | "ABS-15G/A"
  | "ABS-EE"
  | "ABS-EE/A"
  | "ANNLRPT"
  | "ANNLRPT/A"
  | "ARS"
  | "ARS/A"
  | "AW"
  | "AW WD"
  | "C"
  | "C-W"
  | "C-U"
  | "C-U-W"
  | "C/A"
  | "C/A-W"
  | "C-AR"
  | "C-AR-W"
  | "C-AR/A"
  | "C-AR/A-W"
  | "C-TR"
  | "C-TR-W"
  | "CB"
  | "CB/A"
  | "CFPORTAL"
  | "CFPORTAL/A"
  | "CFPORTAL-W"
  | "DEF 14A"
  | "DEF 14C"
  | "DEFA14A"
  | "DEFA14C"
  | "DEFC14A"
  | "DEFC14C"
  | "DEFM14A"
  | "DEFM14C"
  | "DEFN14A"
  | "DEFR14A"
  | "DEFR14C"
  | "DEL AM"
  | "DFAN14A"
  | "DFRN14A"
  | "DSTRBRPT"
  | "DSTRBRPT/A"
  | "SBS DISPUTE NOTICE"
  | "SBS DISPUTE NOTICE/A"
  | "F-1"
  | "F-1/A"
  | "F-10"
  | "F-10/A"
  | "F-10EF"
  | "F-10POS"
  | "F-1MEF"
  | "F-3"
  | "F-3/A"
  | "F-3ASR"
  | "F-3D"
  | "F-3DPOS"
  | "F-3MEF"
  | "F-4"
  | "F-4/A"
  | "F-4EF"
  | "F-4MEF"
  | "F-4 POS"
  | "F-6"
  | "F-6/A"
  | "F-6EF"
  | "F-6 POS"
  | "F-7"
  | "F-7/A"
  | "F-7 POS"
  | "F-8"
  | "F-8/A"
  | "F-80"
  | "F-80/A"
  | "F-8 POS"
  | "F-80POS"
  | "F-9"
  | "F-9/A"
  | "F-9EF"
  | "F-9 POS"
  | "F-N"
  | "F-N/A"
  | "FWP"
  | "F-X"
  | "F-X/A"
  | "N-1"
  | "N-1/A"
  | "N-14"
  | "N-14/A"
  | "N-14 8C"
  | "N-14 8C/A"
  | "N-14MEF"
  | "N-18F1"
  | "N-18F1/A"
  | "N-1 A"
  | "N-1A/A"
  | "N-2"
  | "N-2/A"
  | "N-23C-2"
  | "N-23C-2/A"
  | "N-23C3A"
  | "N-23C3A/A"
  | "N-23C3B"
  | "N-23C3B/A"
  | "N-23C3C"
  | "N-23C3C/A"
  | "N-27D-1"
  | "N-27D-1/A"
  | "N-2ASR"
  | "N-2 POSASR"
  | "N-2MEF"
  | "N-3"
  | "N-3/A"
  | "N-30B-2"
  | "N-30D"
  | "N-30D/A"
  | "N-4"
  | "N-4/A"
  | "N-5"
  | "N-5/A"
  | "N-54A"
  | "N-54A/A"
  | "N-54C"
  | "N-54C/A"
  | "N-6"
  | "N-6/A"
  | "N-6F"
  | "N-6F/A"
  | "N-8A"
  | "N-8A/A"
  | "N-8B-2"
  | "N-8B-2/A"
  | "N-8B-3"
  | "N-8B-3/A"
  | "N-8B-4"
  | "N-8B-4/A"
  | "N-8F"
  | "N-CEN"
  | "N-CEN/A"
  | "NPORT-P"
  | "NPORT-NP"
  | "NPORT-P/A"
  | "NPORT-NP/A"
  | "N-8F/A"
  | "N-CSR"
  | "N-CSR/A"
  | "N-CSRS"
  | "N-CSRS/A"
  | "N-PX"
  | "N-PX/A"
  | "N-PX-FM"
  | "N-PX-FM/A"
  | "N-Q"
  | "N-Q/A"
  | "NSAR-A"
  | "NSAR-A/A"
  | "NSAR-AT"
  | "NSAR-AT/A"
  | "NSAR-B"
  | "NSAR-B/A"
  | "NSAR-BT"
  | "NSAR-BT/A"
  | "NSAR-U"
  | "NSAR-U/A"
  | "NT 10-D"
  | "NT 10-D/A"
  | "NT 10-K"
  | "NT 10-K/A"
  | "NT 10-Q"
  | "NT 10-Q/A"
  | "NT 11-K"
  | "NT 11-K/A"
  | "NT 15D2"
  | "NT 15D2/A"
  | "NT 20-F"
  | "NT 20-F/A"
  | "NT-NCSR"
  | "NT-NCSR/A"
  | "NT-NSAR"
  | "NT-NSAR/A"
  | "N-VP"
  | "N-VP/A"
  | "POS 8C"
  | "POS AM"
  | "POS AMI"
  | "POS EX"
  | "POS462B"
  | "POS462C"
  | "POSASR"
  | "PRE 14A"
  | "PRE 14C"
  | "PREC14A"
  | "PREC14C"
  | "PREM14A"
  | "PREM14C"
  | "PREN14A"
  | "PRER14A"
  | "PRER14C"
  | "PRRN14A"
  | "PX14A6G"
  | "PX14A6N"
  | "QRTLYRPT"
  | "QRTLYRPT/A"
  | "RW"
  | "RW WD"
  | "S-1"
  | "S-1/A"
  | "S-11"
  | "S-11/A"
  | "S-11MEF"
  | "S-1MEF"
  | "S-20"
  | "S-20/A"
  | "S-3"
  | "S-3/A"
  | "S-3ASR"
  | "S-3D"
  | "S-3DPOS"
  | "S-3MEF"
  | "S-4"
  | "S-4/A"
  | "S-4 POS"
  | "S-4EF"
  | "S-4MEF"
  | "S-6"
  | "S-6/A"
  | "S-8 POS"
  | "S-8"
  | "S-B"
  | "S-B/A"
  | "S-BMEF"
  | "SC 13D"
  | "SC 13D/A"
  | "SC 13E1"
  | "SC 13E1/A"
  | "SC 13E3"
  | "SC 13E3/A"
  | "SC 13G"
  | "SC 13G/A"
  | "SC 14D9"
  | "SC 14D9/A"
  | "SC 14F1"
  | "SC 14F1/A"
  | "SC TO-C"
  | "SC TO-I"
  | "SC TO-I/A"
  | "SC TO-T"
  | "SC TO-T/A"
  | "SC13E4F"
  | "SC13E4F/A"
  | "SC14D1F"
  | "SC14D1F/A"
  | "SC14D9C"
  | "SC14D9F"
  | "SC14D9F/A"
  | "SDR-CCO"
  | "SDR-CCO/A"
  | "SH-ER"
  | "SH-ER/A"
  | "SH-NT"
  | "SH-NT/A"
  | "SP 15D2"
  | "SP 15D2/A"
  | "SUPPL"
  | "T-3"
  | "T-3/A"
  | "T-6"
  | "T-6/A"
  | "UNDER"
  | "UNDER/A"
  | "ETR"
  | "N-PX-NT"
  | "N-PX-NT/A"
  | "N-PX-VR"
  | "N-PX-VR/A"
  | "N-PX-CR"
  | "N-PX-CR/A"
  | "N-PXCON"
  | "N-PXCON/A"
  | "N-PXCONP"
  | "N-PXCONP/A"
  | "DRS"
  | "DRS/A"
  | "DRSLTR"
  | "SD"
  | "SD/A"
  | "SF-1"
  | "SF-1/A"
  | "SF-1MEF"
  | "SF-3"
  | "SF-3/A"
  | "SF-3MEF"
  | "DOS"
  | "DOS/A"
  | "DOSLTR"
  | "1-A"
  | "1-A/A"
  | "1-A-W"
  | "1-A-W/A"
  | "1-A POS"
  | "1-K"
  | "1-K/A"
  | "1-Z"
  | "1-Z/A"
  | "1-SA"
  | "1-SA/A"
  | "1-U"
  | "1-U/A"
  | "SDR"
  | "SDR/A"
  | "SDR-A"
  | "SDR-W"
  | "253G1"
  | "253G2"
  | "253G3"
  | "253G4";

// Subject company's IRS employer identification code. Field is 10 characters long which including the dash. Sample: 22-7777777
export type TAX_ID_TYPE = string;

// For certain filings by investment companies, the tag identifies Act or Acts when the form type may be filed under more than one Act. Valid values when required are 33, 34, 40, or 33 40. Choose value from the list displayed when the arrow is selected.
export type ACT_TYPE = "33" | "40" | "33 40" | "34" | "NE";

// Identifies a person to contact if there are questions about the submission (field up to 30 characters).
export type NAME_TYPE = string;

// Identifies a person to contact if there are questions about the submission (field up to 60 characters).
export type NAME_TYPE_60 = string;

// Identifies a person to contact if there are questions about the submission (field up to 150 characters).
export type NAME_TYPE_150 = string;

// Phone number of the contact person; maximum fieldsize is 20 alphanumeric characters. Hyphens may be included to improve readability.
export type PHONE_TYPE = string;

// CONTACT_TYPE ...
export interface CONTACT_TYPE {
  name: NAME_TYPE_150;
  phoneNumber: PHONE_TYPE;
}

// FLAG_TYPE ...
export interface FLAG_TYPE {
  confirmingCopyFlag: boolean;
  delayingAmendmentFlag: boolean;
  overrideInternetFlag: boolean;
  returnCopyFlag: boolean;
  serialFlag: boolean;
}

// NOTIFICATION_TYPE ...
export interface NOTIFICATION_TYPE {
  internetNotificationAddress: string;
}

// Identifies one or more stock exchanges or other self-regulatory organizations on which the issuer's securities are listed or traded. Choose values from the list displayed. If none applies, select the value "NONE".
export type SRO_TYPE =
  | "NONE"
  | "AMEX"
  | "ARCA"
  | "BSE"
  | "CBOE"
  | "CHX"
  | "FINRA"
  | "ISE"
  | "NASD"
  | "NSX"
  | "NYSE"
  | "PCX"
  | "PHLX";

// Identifies one or more stock exchanges or other self-regulatory organizations on which the issuer's securities are listed or traded. Choose values from the list displayed. If none applies, select the value "NONE".
export interface SROS_TYPE {
  sroId: string;
}

// Identifies the investment company type of the filer. Choose a value from the list displayed when the arrow is selected.
export interface INVESTMENT_COMPANY_TYPE {
  isImCompany: boolean;
  invCompanyType: string;
}

// Identifies a module or segment name.
export type MODULE_SEGMENT_NAME_TYPE = string;

// M: is module. S: is segment
export type MODULE_OR_SEGMENT_FLAG = "M" | "S";

// MODULE_SEGMENT_FORM_TYPE ...
export interface MODULE_SEGMENT_FORM_TYPE {
  DOCUMENT_TYPE: DOCUMENT_TYPE;
  SUBMISSION_TYPE: string;
}

// Single module segment type
export interface MODULE_SEGMENT_TYPE {
  modOrSegFlag: string;
  nickName: string;
  cik: string;
  ccc: string;
  documentType: MODULE_SEGMENT_FORM_TYPE;
}

// Group of module segment type elements
export interface MODULES_SEGMENT_TYPE {
  moduleSegment: Array<MODULE_SEGMENT_TYPE>;
}

// Enter the type of this document. Select a value from the list displayed when the arrow is selected. Type any additional characters in the field to accurately specify a validEDGAR document type.
export interface DOCUMENT_TYPE {
  BASE_DOCUMENT_TYPE: BASE_DOCUMENT_TYPE;
  OPEN_DOCUMENT_TYPE: OPEN_DOCUMENT_TYPE;
}

// OPEN_DOCUMENT_TYPE ...
export type OPEN_DOCUMENT_TYPE = string;

// Enter the type of this document. Select a value from the list displayed when the arrow is selected. Type any additional characters in the field to accurately specify a validEDGAR document type.
export type BASE_DOCUMENT_TYPE =
  | "CORRESP"
  | "COVER"
  | "EU-1"
  | "EX-1"
  | "EX-1.01"
  | "EX-10"
  | "EX-100.CAL"
  | "EX-100.DEF"
  | "EX-100.INS"
  | "EX-100.LAB"
  | "EX-100.PRE"
  | "EX-100.REF"
  | "EX-100.SCH"
  | "EX-101.CAL"
  | "EX-101.DEF"
  | "EX-101.INS"
  | "EX-101.LAB"
  | "EX-101.PRE"
  | "EX-101.REF"
  | "EX-101.SCH"
  | "EX-11"
  | "EX-12"
  | "EX-13"
  | "EX-14"
  | "EX-15"
  | "EX-16"
  | "EX-17"
  | "EX-18"
  | "EX-19"
  | "EX-2"
  | "EX-2.01.CAL"
  | "EX-2.01.DEF"
  | "EX-2.01.INS"
  | "EX-2.01.LAB"
  | "EX-2.01.PRE"
  | "EX-2.01.REF"
  | "EX-2.01.SCH"
  | "EX-20"
  | "EX-21"
  | "EX-22"
  | "EX-23"
  | "EX-24"
  | "EX-25"
  | "EX-25/A"
  | "EX-26"
  | "EX-3"
  | "EX-31"
  | "EX-32"
  | "EX-33"
  | "EX-34"
  | "EX-35"
  | "EX-36"
  | "EX-4"
  | "EX-5"
  | "EX-7"
  | "EX-8"
  | "EX-9"
  | "EX-95"
  | "EX-96"
  | "EX-99"
  | "EX-99.1 CHARTER"
  | "EX-99.10 12B1 PLAN"
  | "EX-99.11 OPIN COUNSL"
  | "EX-99.12 REV RULING"
  | "EX-99.12 TAX OPINION"
  | "EX-99.13 OTH CONTRCT"
  | "EX-99.14 OTH CONSENT"
  | "EX-99.15 OTH FIN ST"
  | "EX-99.16 PWR OF ATTY"
  | "EX-99.17 (as approp)"
  | "EX-99.2 BYLAWS"
  | "EX-99.2 OPIN COUNSEL"
  | "EX-99.2A CHARTER"
  | "EX-99.2B BYLAWS"
  | "EX-99.2C VOTING TRST"
  | "EX-99.2D HOLDERS RTS"
  | "EX-99.2E DIV REIN PL"
  | "EX-99.2F SUBSID DEBT"
  | "EX-99.2G ADVSR CONTR"
  | "EX-99.2H DISTR CONTR"
  | "EX-99.2I O&D BENEFTS"
  | "EX-99.2J CUST CONTR"
  | "EX-99.2K OTH CONTRCT"
  | "EX-99.2L OPIN COUNSL"
  | "EX-99.2M CNSNT SRVCE"
  | "EX-99.2N OTH CONSENT"
  | "EX-99.2O OTH FIN ST"
  | "EX-99.2P STOCK LTR"
  | "EX-99.2Q RETRMT PLAN"
  | "EX-99.2R CODE ETH"
  | "EX-99.20 OPIN COUNSL"
  | "EX-99.21 7-R"
  | "EX-99.22 BD REG"
  | "EX-99.3 OTHER FIN ST"
  | "EX-99.3 VOTING TRUST"
  | "EX-99.31 MA-NR"
  | "EX-99.32 APP CRT DOC"
  | "EX-99.33 APP REG DOC"
  | "EX-99.34 OPIN COUNSL"
  | "EX-99.3a BD-DIR-RESO"
  | "EX-99.3b BYLAWS"
  | "EX-99.3c CUST-AGRMET"
  | "EX-99.3d ADVSR CONTR"
  | "EX-99.3e UNDER CONTR"
  | "EX-99.3f CONTRACTS"
  | "EX-99.3g APPLICATION"
  | "EX-99.3h BYLAWS INS"
  | "EX-99.3i REINS CONTR"
  | "EX-99.3j PROFIT SHAR"
  | "EX-99.3k ADMIN CONTR"
  | "EX-99.3l OTH MAT CON"
  | "EX-99.3m LEGAL OPIN"
  | "EX-99.3n OTH OPINION"
  | "EX-99.3o OMITD FIN"
  | "EX-99.3p INIT CAP AG"
  | "EX-99.3q CODE ETH"
  | "EX-99.3r FORM OF ISP"
  | "EX-99.4 ACQ AGREEMNT"
  | "EX-99.4 UNREG ISSUER"
  | "EX-99.4a BD-DIR-RESO"
  | "EX-99.4b CUST-AGRMET"
  | "EX-99.4c UNDER CONTR"
  | "EX-99.4d CONTRACTS"
  | "EX-99.4e APPLICATION"
  | "EX-99.4f DEP CERT/BY"
  | "EX-99.4g REINS CONTR"
  | "EX-99.4h PARTIC AGR"
  | "EX-99.4i ADMIN CONTR"
  | "EX-99.4j OTH MAT CON"
  | "EX-99.4k LEGAL OPIN"
  | "EX-99.4l OTH OPINION"
  | "EX-99.4m OMITD FIN"
  | "EX-99.4n INIT CAP AG"
  | "EX-99.4o FORM OF ISP"
  | "EX-99.4 ACQ AGREEMNT"
  | "EX-99.4 UNREG ISSUER"
  | "EX-99.5 HOLDERS RTS"
  | "EX-99.6 ADVSER CONTR"
  | "EX-99.7 DISTR CONTR"
  | "EX-99.77B ACCT LTTR"
  | "EX-99.77C VOTES"
  | "EX-99.77D POLICIES"
  | "EX-99.77E LEGAL"
  | "EX-99.77F CHNG DEBT"
  | "EX-99.77G DEFAULTS"
  | "EX-99.77H CHNG CNTRL"
  | "EX-99.77I NEW SECUR"
  | "EX-99.77J REVALUATN"
  | "EX-99.77K CHNG ACCNT"
  | "EX-99.77L NEW ACCTNG"
  | "EX-99.77M MERGERS"
  | "EX-99.77N RULE 2A-7"
  | "EX-99.77O RULE 10F-3"
  | "EX-99.77P EXMPT INFO"
  | "EX-99.77Q1 OTHR EXHB"
  | "EX-99.77Q2 ITEM 405"
  | "EX-99.8 O&D BENEFTS"
  | "EX-99.9 CUST CONTRCT"
  | "EX-99.906 CERT"
  | "EX-99.a BD-DIR-RESOL"
  | "EX-99.a CHARTER"
  | "EX-99.A1 INDNTR ORGN"
  | "EX-99.A10 PERIODC PP"
  | "EX-99.A11 CODE ETH"
  | "EX-99.A2 INDNTR PMT"
  | "EX-99.A3A DIST CONTR"
  | "EX-99.A3B DEALER AGR"
  | "EX-99.A3C SCH COMMIS"
  | "EX-99.A4 OTHER AGRMT"
  | "EX-99.A5 FORM/SECRTY"
  | "EX-99.A6 CERT/BYLAWS"
  | "EX-99.A7 INSR POLICY"
  | "EX-99.A8 DEPOSIT AGR"
  | "EX-99.A9 OTHER CONTR"
  | "EX-99.b BYLAWS"
  | "EX-99.b CUST-AGRMETS"
  | "EX-99.B1 NOTIC/SHLDR"
  | "EX-99.B2 ANRPT/SHLDR"
  | "EX-99.c HOLDERS RTS"
  | "EX-99.c UNDER CONTRT"
  | "EX-99.C1 ACCT CONSNT"
  | "EX-99.C2 EVAL CONSNT"
  | "EX-99.C3 RTG AGY OPN"
  | "EX-99.C4 TAX OPINION"
  | "EX-99.C5 REV RULING"
  | "EX-99.C6 OTHER OPIN"
  | "EX-99.CERT"
  | "EX-99.CODE ETH"
  | "EX-99.d ADVSR CONTR"
  | "EX-99.d CONTRACTS"
  | "EX-99.e APPLICATIONS"
  | "EX-99.e UNDR CONTR"
  | "EX-99.f BONUS PROFIT"
  | "EX-99.f DEP CERT/BYL"
  | "EX-99.g CUST AGREEMT"
  | "EX-99.g REINS CONTRT"
  | "EX-99.h OTH MAT CONT"
  | "EX-99.h PARTIC AGREE"
  | "EX-99.i ADMIN CONTRT"
  | "EX-99.i LEGAL OPININ"
  | "EX-99.j OTH MAT CONT"
  | "EX-99.j OTHER OPININ"
  | "EX-99.k LEGAL OPININ"
  | "EX-99.k OMT FIN STAT"
  | "EX-99.l ACTUARIAL OP"
  | "EX-99.l INT CAP AGRE"
  | "EX-99.m 12B-1 PLAN"
  | "EX-99.m CALCULATION"
  | "EX-99.n 18F-3 PLAN"
  | "EX-99.n OTH OPINIONS"
  | "EX-99.o OMITD FIN ST"
  | "EX-99.p CODE ETH"
  | "EX-99.p INIT CAP AGR"
  | "EX-99.q REDEEM EXEMP"
  | "EX-99.r FORM OF ISP"
  | "EX-99.A SDR AGRMNT"
  | "EX-99.A SDR SUMMARY"
  | "EX-99.B SDR"
  | "EX-99.C SDR"
  | "EX-99.D SDR"
  | "EX-99.E SDR"
  | "EX-99.F SDR"
  | "EX-99.G SDR"
  | "EX-99.H SDR"
  | "EX-99.I SDR CNTRCT"
  | "EX-99.I SDR SUMMARY"
  | "EX-99.IND PUB ACCT"
  | "EX-99.J SDR"
  | "EX-99.K SDR"
  | "EX-99.K SDR.INS"
  | "EX-99.K SDR.SCH"
  | "EX-99.K SDR.PRE"
  | "EX-99.K SDR.LAB"
  | "EX-99.K SDR.CAL"
  | "EX-99.K SDR.REF"
  | "EX-99.L SDR"
  | "EX-99.L SDR.INS"
  | "EX-99.L SDR.SCH"
  | "EX-99.L SDR.PRE"
  | "EX-99.L SDR.LAB"
  | "EX-99.L SDR.CAL"
  | "EX-99.L SDR.REF"
  | "EX-99.M SDR"
  | "EX-99.N SDR"
  | "EX-99.O SDR"
  | "EX-99.P SDR"
  | "EX-99.Q SDR"
  | "EX-99.R SDR"
  | "EX-99.S SDR"
  | "EX-99.T SDR"
  | "EX-99.U SDR"
  | "EX-99.V SDR"
  | "EX-99.W SDR"
  | "EX-99.X SDR"
  | "EX-99.Y SDR"
  | "EX-99.Z SDR"
  | "EX-99.AA SDR"
  | "EX-99.BB SDR"
  | "EX-99.CC SDR"
  | "EX-99.DD SDR"
  | "EX-99.EE SDR"
  | "EX-99.FF SDR"
  | "EX-99.GG SDR"
  | "EX-99.HH SDR"
  | "EX-99.II SDR"
  | "EX-99.Rule23C1"
  | "EX-102"
  | "EX-103"
  | "EX-106"
  | "EX-FILING FEES"
  | "GRAPHIC"
  | "ORGCHART"
  | "EX1SA-1 UNDR AGMT"
  | "EX1SA-2A CHARTER"
  | "EX1SA-2B BYLAWS"
  | "EX1SA-3 HLDRS RTS"
  | "EX1SA-4 SUBS AGMT"
  | "EX1SA-5 VOTG TRST"
  | "EX1SA-6 MAT CTRCT"
  | "EX1SA-7 ACQ AGMT"
  | "EX1SA-8 ESCW AGMT"
  | "EX1SA-9 ACCT LTR"
  | "EX1SA-10 PWR ATTY"
  | "EX1SA-11 CONSENT"
  | "EX1SA-12 OPN CNSL"
  | "EX1SA-13 TST WTRS"
  | "EX1SA-14 CNSNT SV"
  | "EX1SA-17 GNTR/ISSR"
  | "EX1U-1 UNDR AGMT "
  | "EX1U-2A CHARTER"
  | "EX1U-2B BYLAWS"
  | "EX1U-3 HLDRS RTS"
  | "EX1U-4 SUBS AGMT"
  | "EX1U-5 VOTG TRST"
  | "EX1U-6 MAT CTRCT"
  | "EX1U-7 ACQ AGMT"
  | "EX1U-8 ESCW AGMT"
  | "EX1U-9 ACCT LTR"
  | "EX1U-10 PWR ATTY"
  | "EX1U-11 CONSENT"
  | "EX1U-12 OPN CNSL"
  | "EX1U-13 TST WTRS"
  | "EX1U-14 CNSNT SV"
  | "EX1U-17 GNTR/ISSR"
  | "PART II AND III"
  | "EX1A-1 UNDR AGMT"
  | "EX1A-2A CHARTER"
  | "EX1A-2B BYLAWS"
  | "EX1A-3 HLDRS RTS"
  | "EX1A-4 SUBS AGMT"
  | "EX1A-5 VOTG TRST"
  | "EX1A-6 MAT CTRCT"
  | "EX1A-7 ACQ AGMT"
  | "EX1A-8 ESCW AGMT"
  | "EX1A-9 ACCT LTR"
  | "EX1A-10 PWR ATTY"
  | "EX1A-11 CONSENT"
  | "EX1A-12 OPN CNSL"
  | "EX1A-13 TST WTRS"
  | "EX1A-14 CNSNT SV"
  | "EX1A-17 GNTR/ISSR"
  | "PART II"
  | "EX1K-1 UNDR AGMT"
  | "EX1K2A CHARTER"
  | "EX1K-2B BYLAWS"
  | "EX1K-3 HLDRS RTS"
  | "EX1K-4 SUBS AGMT"
  | "EX1K-5 VOTG TRST"
  | "EX1K-6 MAT CTRCT"
  | "EX1K-7 ACQ AGMT"
  | "EX1K-8 ESCW AGMT"
  | "EX1K-9 ACCT LTR"
  | "EX1K-10 PWR ATTY"
  | "EX1K-11 CONSENT"
  | "EX1K-12 OPN CNSL"
  | "EX1K-13 TST WTRS"
  | "EX1K-14 CNSNT SV"
  | "EX1K-17 GNTR/ISSR"
  | "EX-99.E1 NRSRO"
  | "EX-99.E2 NRSRO"
  | "EX-99.E3 NRSRO"
  | "EX-99.E4 NRSRO"
  | "EX-99.E5 NRSRO"
  | "EX-99.E6 NRSRO"
  | "EX-99.E7 NRSRO"
  | "EX-99.E8 NRSRO"
  | "EX-99.E9 NRSRO"
  | "EX-99.Ra1 NRSRO"
  | "EX-99.Ra2 NRSRO"
  | "EX-99.Ra3 NRSRO"
  | "EX-99.Ra4 NRSRO"
  | "EX-99.Ra5 NRSRO"
  | "EX-99.Ra6 NRSRO"
  | "EX-99.Ra6S NRSRO"
  | "EX-99.Ra7 NRSRO"
  | "EX-99.Ra7S NRSRO"
  | "EX-99.Ra8 NRSRO"
  | "SDR-CR"
  | "SDR-FR"
  | "SDR-CR/A"
  | "SDR-FR/A"
  | "LEGAL PROCEEDINGS"
  | "FINANCIAL SUPPORT"
  | "INTERNAL CONTROL RPT"
  | "CHG ACCT PRINCIPLES"
  | "EXEMPT ORDER INFO"
  | "OTHER REQUIRED INFO"
  | "MATERIAL AMENDMENTS"
  | "INST DEFINING RIGHTS"
  | "ADVISORY CONTRACTS"
  | "ITEM 405 REG S-K"
  | "CODE OF ETHICS"
  | "NPORT-EX"
  | "ADD EXHB";

// SUB_DOCUMENT_TYPE ...
export interface SUB_DOCUMENT_TYPE {
  DOCUMENT_TYPE: DOCUMENT_TYPE;
  SUBMISSION_TYPE: string;
}

// File names must be upper or lower case and nolonger than thirty-two (32) characters in length. The names must start with a letter (a-z) or a number and may contain numbers (0-9) with no spaces. File names may contain any number of periods (.), hyphens (-), and underscore (_) characters and must end with *.htm, *.txt, *.pdf, *.fil, *.jpg, *.gif, *.xml or *.xsd extensions.
export type DOCUMENT_NAME_TYPE = string;

// An optional field offering you the opportunity todescribe the attached document. Field is up to 255 characters.
export type DOCUMENT_DESCRIPTION_TYPE = string;

// DOCUMENT_MIME_BLOCK_TYPE ...
export type DOCUMENT_MIME_BLOCK_TYPE = string;

// Document names must be lower case and no longer than thirty-two (32) characters in length. The names must start with a letter (a-z) and may contain numbers (0-9) with no spaces. Document names may contain one period (.), one hyphen (-), and one underscore (_) character and must end with *.htm, *.txt, *.pdf, *.fil, *.jpg, *.gif, *.xml or *.xsd extensions.
export interface EDGAR_DOCUMENT_TYPE {
  conformedName: string;
  conformedDocumentType: SUB_DOCUMENT_TYPE;
  relatedFormType: string;
  description: string;
  contents: string;
}

// EDGAR_DOCUMENTS_TYPE ...
export interface EDGAR_DOCUMENTS_TYPE {
  document: Array<EDGAR_DOCUMENT_TYPE>;
}

// Document names must be lower case and no longer
// than thirty-two (32) characters in length. The names must start with
// a letter (a-z) and may contain numbers (0-9) with no spaces.
// Document names may contain one period (.), one hyphen (-), and one
// underscore (_) character and must end with *.htm, *.txt, *.pdf,
// *.fil, *.jpg, *.gif, *.xml or *.xsd extensions.
export interface CONFIDENTIAL_DOCUMENT_TYPE {
  conformedName: string;
  conformedDocumentType: SUB_DOCUMENT_TYPE;
  description: string;
  contents: string;
  confidentiality: boolean;
}

// CONFIDENTIAL_DOCUMENTS_TYPE ...
export interface CONFIDENTIAL_DOCUMENTS_TYPE {
  document: Array<CONFIDENTIAL_DOCUMENT_TYPE>;
}

// Document names must be lower case and no longer than thirty-two (32) characters in length. The names must start with a letter (a-z) and may contain numbers (0-9) with no spaces. Document names may contain one period (.), one hyphen (-), and one underscore (_) character and must end with *.htm, *.txt, *.pdf, *.fil, *.jpg, *.gif, *.xml or *.xsd extensions.
export interface CONFIDENTIAL_DOCUMENT_TYPE1 {
  conformedName: string;
  conformedDocumentType: SUB_DOCUMENT_TYPE;
  description: string;
  contents: string;
  confidentiality: boolean;
}

// CONFIDENTIAL_DOCUMENTS_TYPE1 ...
export interface CONFIDENTIAL_DOCUMENTS_TYPE1 {
  document: Array<CONFIDENTIAL_DOCUMENT_TYPE1>;
}

// The name of the depository bank (field up to 50 characters).
export type DEPOSITORY_TYPE = string;

// DECIMAL_TYPE20_8 ...
export type DECIMAL_TYPE20_8 = number;

// DECIMAL_TYPE7_2_NONNEGATIVE ...
export type DECIMAL_TYPE7_2_NONNEGATIVE = number;

// DECIMAL_TYPE14_2 ...
export type DECIMAL_TYPE14_2 = number;

// DECIMAL_TYPE14_2_FIXED ...
export type DECIMAL_TYPE14_2_FIXED = number;

// DECIMAL_TYPE15_3 ...
export type DECIMAL_TYPE15_3 = number;

// DECIMAL_TYPE16_4 ...
export type DECIMAL_TYPE16_4 = number;

// DECIMAL_TYPE12_5_FIXED ...
export type DECIMAL_TYPE12_5_FIXED = number;

// DECIMAL_TYPE7_5_FIXED ...
export type DECIMAL_TYPE7_5_FIXED = number;

// DECIMAL_TYPE7_2_FIXED ...
export type DECIMAL_TYPE7_2_FIXED = number;

// YES_NO_TYPE ...
export enum YES_NO_TYPE {
  Y = "Y",
  N = "N",
}

// YEAR_TYPE ...
export type YEAR_TYPE = string;

// Updated fiscal year end value. Acceptable values are in the format MM/DD, for example, 12/31, 03/30, 06/30, 2/28.
export type FISCAL_YEAR_TYPE_2 = string;

// FISCAL_YEAR_TYPE ...
export interface FISCAL_YEAR_TYPE {
  fiscalYearEnd: string;
}

// STRING_1_TYPE ...
export type STRING_1_TYPE = string;

// STRING_10_TYPE ...
export type STRING_10_TYPE = string;

// STRING_12_TYPE ...
export type STRING_12_TYPE = string;

// STRING_20_TYPE ...
export type STRING_20_TYPE = string;

// STRING_25_TYPE ...
export type STRING_25_TYPE = string;

// STRING_30_TYPE ...
export type STRING_30_TYPE = string;

// STRING_40_TYPE ...
export type STRING_40_TYPE = string;

// STRING_50_TYPE ...
export type STRING_50_TYPE = string;

// STRING_60_TYPE ...
export type STRING_60_TYPE = string;

// STRING_80_TYPE ...
export type STRING_80_TYPE = string;

// STRING_100_TYPE ...
export type STRING_100_TYPE = string;

// STRING_150_TYPE ...
export type STRING_150_TYPE = string;

// STRING_200_TYPE ...
export type STRING_200_TYPE = string;

// STRING_250_TYPE ...
export type STRING_250_TYPE = string;

// STRING_255_TYPE ...
export type STRING_255_TYPE = string;

// STRING_256_TYPE ...
export type STRING_256_TYPE = string;

// STRING_4000_TYPE ...
export type STRING_4000_TYPE = string;

// STRING_1K_TYPE ...
export type STRING_1K_TYPE = string;

// STRING_1K_RESTRICTED_TYPE ...
export type STRING_1K_RESTRICTED_TYPE = string;

// STRING_10K_TYPE ...
export type STRING_10K_TYPE = string;

// STRING_20K_TYPE ...
export type STRING_20K_TYPE = string;

// STREET_TYPE ...
export type STREET_TYPE = string;

// ZIP_TYPE ...
export type ZIP_TYPE = string;

// ADDRESS_TYPE ...
export interface ADDRESS_TYPE {
  street1: string;
  street2: string;
  city: string;
  stateOrCountry: string;
  zipCode: string;
}

// FILER_TYPE ...
export interface FILER_TYPE {
  filerId: string;
  filerCcc: string;
  filerFileNumber: string;
}

// ID_TYPE ...
export type ID_TYPE = string;

// OTHER_TYPE ...
export interface OTHER_TYPE {
  otherSpecification: string;
}

export type US_COUNTRY_CODE = "X1";
// STATE_COUNTRY_TYPE_LIST ...
export interface STATE_COUNTRY_TYPE_LIST {
  US_COUNTRY_CODE: US_COUNTRY_CODE;
  US_STATE_CODES: string;
  NON_US_COUNTRY_CODES: string;
}

// STATE_COUNTRY_TYPE ...
export interface STATE_COUNTRY_TYPE {
  stateOrCountry: string;
}

// SIGNATURE_TYPE ...
export interface SIGNATURE_TYPE {
  dateSigned: string;
  nameOfApplicant: string;
  signature: string;
  signerName: string;
  title: string;
}

// NAME_TYPE_2 ...
export interface NAME_TYPE_2 {
  firstName: string;
  middleName: string;
  lastName: string;
}

// SIGNATURE_TYPE_2 ...
export interface SIGNATURE_TYPE_2 {
  signature: string;
  signerName: string;
  title: string;
  date: string;
}

// SIGNATURE_TYPE_3 ...
export interface SIGNATURE_TYPE_3 {
  signature: string;
  signerName: string;
  title: string;
  date: string;
}

// FILER_CREDENTIALS ...
export interface FILER_CREDENTIALS {
  cik: string;
  ccc: string;
}

// EDGARLITE_ADDRESS_TYPE ...
export interface EDGARLITE_ADDRESS_TYPE {
  street1: string;
  street2: string;
  city: string;
  stateOrCountryCode: string;
  stateOrCountry: string;
  zipCode: string;
}

// CONTACT_EMAIL_TYPE ...
export interface CONTACT_EMAIL_TYPE {
  contactName: string;
  contactPhoneNumber: EDGAR_PHONE_TYPE;
  contactEmailAddress: string;
}

// SIGNATURE_TYPE_4 ...
export interface SIGNATURE_TYPE_4 {
  signatureName: string;
  signatureTitle: string;
  signaturePhoneNumber: EDGAR_PHONE_TYPE;
  signatureDate: string;
}

// minLength 1
// maxLength 20
// pattern [a-zA-Z0-9\s#(),.\-]{1,20}
export type EDGAR_PHONE_TYPE = string;

export type ABS_ASSET_CLASS_TYPE =
  | "Residential mortgages - Prime"
  | "Residential mortgages - Non-Prime"
  | "Residential mortgages - HELOC"
  | "Residential mortgages - Reverse Mortgages"
  | "Residential mortgages - Manufactured Housing"
  | "Residential mortgages - Other/Combined"
  | "Commercial mortgages"
  | "Auto loans"
  | "Auto leases"
  | "Equipment leases"
  | "Equipment loans"
  | "Student loans"
  | "Floorplan financings"
  | "Debt Securities"
  | "Resecuritization"
  | "Credit card"
  | "Other";

// ABS_ASSET_CLASS_TYPES ...
export interface ABS_ASSET_CLASS_TYPES {
  absAssetClass: Array<ABS_ASSET_CLASS_TYPE>;
}

export type ABS_SUB_ASSET_CLASS_TYPE =
  | "Residential mortgages - Prime"
  | "Residential mortgages - Non-Prime"
  | "Residential mortgages - HELOC"
  | "Residential mortgages - Reverse Mortgages"
  | "Residential mortgages - Manufactured Housing"
  | "Residential mortgages - Other/Combined"
  | "Commercial mortgages"
  | "Auto loans"
  | "Auto leases"
  | "Equipment leases"
  | "Equipment loans"
  | "Student loans"
  | "Floorplan financings"
  | "Debt Securities"
  | "Credit card"
  | "Other";

// ABS_SUB_ASSET_CLASS_TYPES ...
export interface ABS_SUB_ASSET_CLASS_TYPES {
  absSubAssetClass: Array<ABS_SUB_ASSET_CLASS_TYPE>;
}

// IRS_OR_SSN ...
export interface IRS_OR_SSN {
  irsNum: string;
  ssn: SSN_TYPE;
}

// INDIVIDUAL_NAME_TYPE ...
export interface INDIVIDUAL_NAME_TYPE {
  prefix: string;
  firstName: string;
  middleName: string;
  lastName: string;
  suffix: string;
}

// EXACT_OR_EXPLANATION ...
export interface EXACT_OR_EXPLANATION {
  date: string;
  exactOrExplanation: EXACT_OR_EXPLANATION_OPTIONS;
  explanationInfo: string;
}
// \d{2,2}/\d{4,4}
export type DATE_MM_YYYY_TYPE = string;

export type MONTH_TYPE =
  | "January"
  | "February"
  | "March"
  | "April"
  | "May"
  | "June"
  | "July"
  | "August"
  | "September"
  | "October"
  | "November"
  | "December";

// Min length 1, max length 9
export type CRD_NUMBER_TYPE = string;

export type EXACT_OR_EXPLANATION_OPTIONS = "Exact" | "Explanation";

// \d{3}-\d{2}-\d{4}
export type SSN_TYPE = string;

// maxLength 3
export type STRING_NUMERIC_3_TYPE = string;
