// Code generated by xgen. DO NOT EDIT.

import * as common from './common';

export type APPEALED_TO_ENTITY_TYPE = 'SEC' | 'SRO' | 'State Court' | 'Federal Court';

export type CRIMINAL_DISPOSITION_OPTION_TYPE = 'Convicted' | 'Acquitted' | 'Dismissed' | 'Pretrial' | 'Other';

export type BOND_DISPOSITION_OPTION_TYPE = 'Denied' | 'Payout' | 'Revoked';

export type LIEN_RESOLVED_TYPE = 'Discharged' | 'Released' | 'Removed' | 'Satisfied';

export type PRINCIPAL_PRODUCT_OPTION_TYPE =
  | 'Annuity(ies) - Fixed'
  | 'Annuity(ies) - Variable'
  | 'CD(s)'
  | 'Commodity Option(s)'
  | 'Debt - Asset Backed'
  | 'Debt - Corporate'
  | 'Debt - Government'
  | 'Debt - Municipal'
  | 'Derivative(s)'
  | 'Direct Investment(s) - DPP & LP Interest(s)'
  | 'Equity - OTC'
  | 'Equity Listed (Common & Preferred Stock)'
  | 'Futures - Commodity'
  | 'Futures - Financial'
  | 'Index Option(s)'
  | 'Insurance'
  | 'Investment Contract(s)'
  | 'Money Market Fund(s)'
  | 'Mutual Fund(s)'
  | 'No Product'
  | 'Options'
  | 'Penny Stock(s)'
  | 'Unit Investment Trust(s)';

export type SANCTIONS_ORDERED_OPTION_TYPE =
  | 'Revocation/Expulsion/Denial'
  | 'Censure'
  | 'Cease and Desist/Injunctoin'
  | 'Disgorgement/Restitution'
  | 'Bar'
  | 'Suspension';

export type PRINCIPAL_SANCTION_RELIEF_BASE = 'Cease and Desist' | 'Disgorgement' | 'Injunction' | 'Restitution';

export type PRINCIPAL_SANCTION_RELIEF_BASE_2 =
  | 'Cease and Desist (Private/Civil Complaint)'
  | 'Restraining Order'
  | 'Injunction'
  | 'Disgorgement'
  | 'Civil Penalty(ies)/Fine(s)'
  | 'Restitution'
  | 'Money Damages'
  | 'Other';

export type PRINCIPAL_SANCTION_TYPE =
  | 'Civl and Administrative Penalty(ies)/Fines)'
  | 'Bar'
  | 'Censure'
  | 'Denial'
  | 'Expulsion'
  | 'Prohibition'
  | 'Reprimand'
  | 'Revocation'
  | 'Suspension'
  | 'Undertaking';

export type REGULATOR_INITIATED_OPTION_TYPE = 'SEC' | 'Other Federal' | 'State' | 'SRO' | 'Foreign';

// APPLICANT_INFO ...
export interface APPLICANT_INFO {
  nameOfApplicant: string;
  applicantCRD: common.CRD_NUMBER_TYPE;
}

// CA_PRINCIPAL_INFO ...
export interface CA_PRINCIPAL_INFO {
  name: NAME_OPTION_TYPE;
  crdNo: common.CRD_NUMBER_TYPE;
  controlAffiliateType: FIRM_INDIVIDUAL_TYPE;
  isRegistered: common.YES_NO_TYPE;
}

// FIRM_INDIVIDUAL_TYPE ...
export enum FIRM_INDIVIDUAL_TYPE {
  firm = 'Firm',
  individual = 'Individual',
}

// NAME_OPTION_TYPE ...
export interface NAME_OPTION_TYPE {
  orgName: common.ENTITY_NAME_TYPE;
  individualName: common.NAME_TYPE_2;
}

// PERSON_ENTITY_OPTION_TYPE ...
export enum PERSON_ENTITY_OPTION_TYPE {
  applicant = 'The Applicant',
  applicantAndCa = 'Applicant and one or more affiliate(s)',
  controlAffiliate = 'One or more control affiliate(s)',
}

// DRP_PART1_TYPE ...
export interface DRP_PART1_TYPE {
  personOrEntity: PERSON_ENTITY_OPTION_TYPE;
  applicantInfo: APPLICANT_INFO;
  controlAffiliatePrincipalInfo: CA_PRINCIPAL_INFO;
  isDRPSubmittedForEvent: common.YES_NO_TYPE;
}

// APPEALED_TO_TYPE ...
export interface APPEALED_TO_TYPE {
  date: common.DATE_TYPE;
  appealedTo: APPEALED_TO_ENTITY_TYPE;
  appealedToCourtName: common.STRING_150_TYPE;
}

// CHARGED_ORGANIZATION ...
export interface CHARGED_ORGANIZATION {
  nameOfOrg: common.STRING_150_TYPE;
  positionTitleOrRelationship: common.STRING_60_TYPE;
  isOrgInvestmentRelated: common.YES_NO_TYPE;
}

// CHARGES_WHERE_BROUGHT_IN ...
export interface CHARGES_WHERE_BROUGHT_IN {
  nameOfCourt: common.STRING_150_TYPE;
  city: common.STRING_150_TYPE;
  stateOrCountry: common.STATE_COUNTRY_TYPE;
  docketOrCaseNo: common.STRING_25_TYPE;
  bankruptcyChapterNo: common.STRING_50_TYPE;
}

// EVENT_STATUS_TYPE ...
export enum EVENT_STATUS_TYPE {
  pending = 'Pending',
  onAppeal = 'OnAppeal',
  final = 'Final',
}

// EXPLANATION_INFO ...
export interface EXPLANATION_INFO {
  explanation: 'Explanation';
  provideExplanation: common.STRING_255_TYPE;
}

// EXACT_OR_EXPLANATION ...
export interface EXACT_OR_EXPLANATION {
  date: common.DATE_TYPE;
  exact: 'Exact';
  explanationInfo: EXPLANATION_INFO;
}

// MONETARY_SANCTION_TYPE ...
export interface MONETARY_SANCTION_TYPE {
  monetarySanction: 'MonetarySanction';
  amount: common.DECIMAL_TYPE14_2_FIXED;
}

// PRINCIPAL_PRODUCT_TYPE ...
export interface PRINCIPAL_PRODUCT_TYPE {
  principalOption: PRINCIPAL_PRODUCT_OPTION_TYPE;
  otherProducts: common.OTHER_TYPE;
}

// SANCTIONS_ORDERED_OPTIONS_TYPE ...
export interface SANCTIONS_ORDERED_OPTIONS_TYPE {
  monetarySanctionOption: MONETARY_SANCTION_TYPE;
  sanctionsOptions: Array<SANCTIONS_ORDERED_OPTION_TYPE>;
}

// SANCTIONS_ORDERED_TYPE ...
export interface SANCTIONS_ORDERED_TYPE {
  sanctionsOrderedOptions: SANCTIONS_ORDERED_OPTIONS_TYPE;
  otherSanctions: common.STRING_255_TYPE;
  sanctionDetail: common.STRING_255_TYPE;
}

// SANCTIONS_ORDERED_TYPE_2 ...
export interface SANCTIONS_ORDERED_TYPE_2 {
  sanctionsOrderedOptions: SANCTIONS_ORDERED_OPTIONS_TYPE;
  otherSanctions: common.STRING_10K_TYPE;
  sanctionDetail: common.STRING_10K_TYPE;
}

// FELONY_MISDEMEANOR_TYPE ...
export enum FELONY_MISDEMEANOR_TYPE {
  felony = 'Felony',
  misdemeanor = 'Misdemeanor',
}

// EVENT_DISC_DETAIL_TYPE ...
export interface EVENT_DISC_DETAIL_TYPE {
  charge: common.STRING_255_TYPE;
  numberOfCounts: common.STRING_NUMERIC_3_TYPE;
  felonyOrMisdemeanor: FELONY_MISDEMEANOR_TYPE;
  plea: common.STRING_255_TYPE;
  isMunicipalAdvisorRelated: common.YES_NO_TYPE;
  isInvestmentRelated: common.YES_NO_TYPE;
  productType: common.STRING_255_TYPE;
  investmentProductType: common.STRING_255_TYPE;
  amendedDate: common.DATE_TYPE;
}

// EVENT_DISC_DETAILS_TYPE ...
export interface EVENT_DISC_DETAILS_TYPE {
  eventDiscDetail: Array<EVENT_DISC_DETAIL_TYPE>;
}

// DISPOSITION_DISC_DETAIL_TYPE ...
export interface DISPOSITION_DISC_DETAIL_TYPE {
  charge: common.STRING_255_TYPE;
  dispositionType: CRIMINAL_DISPOSITION_OPTION_TYPE;
  date: common.DATE_TYPE;
  sentencePenalty: common.STRING_60_TYPE;
  duration: common.STRING_10_TYPE;
  startDatePenalty: common.DATE_TYPE;
  penaltyFineAmout: common.DECIMAL_TYPE14_2_FIXED;
  datePaid: common.DATE_TYPE;
}

// DISPOSITION_DISC_DETAILS_TYPE ...
export interface DISPOSITION_DISC_DETAILS_TYPE {
  dispositionDiscDetail: Array<DISPOSITION_DISC_DETAIL_TYPE>;
}

// CRIMINAL_DRP_PART2_TYPE ...
export interface CRIMINAL_DRP_PART2_TYPE {
  chargedOrg: CHARGED_ORGANIZATION;
  chargesBroughtIn: CHARGES_WHERE_BROUGHT_IN;
  firstCharged: EXACT_OR_EXPLANATION;
  eventDiscDetails: EVENT_DISC_DETAILS_TYPE;
  isAnyChargeFelony: common.YES_NO_TYPE;
  currentStatusOfEvent: EVENT_STATUS_TYPE;
  eventStatusDate: EXACT_OR_EXPLANATION;
  dispositionDisclosureDetail: DISPOSITION_DISC_DETAILS_TYPE;
  summaryOfCircum: common.STRING_255_TYPE;
}

// CRIMINAL_DRP_TYPE ...
export interface CRIMINAL_DRP_TYPE {
  criminalDRPPart1: DRP_PART1_TYPE;
  criminalDRPPart2: CRIMINAL_DRP_PART2_TYPE;
}

// CRIMINAL_DRP_TYPES ...
export interface CRIMINAL_DRP_TYPES {
  criminalDRP: Array<CRIMINAL_DRP_TYPE>;
}

// CRIMINAL_DISCLOSURE_TYPE ...
export interface CRIMINAL_DISCLOSURE_TYPE {
  isConvictedFelony: common.YES_NO_TYPE;
  isChargedFelony: common.YES_NO_TYPE;
  isConvictedMisdemeanor: common.YES_NO_TYPE;
  isChargedMisdemeanor: common.YES_NO_TYPE;
  criminalDisclosureDetails: CRIMINAL_DRP_TYPES;
}

// SEC_CFTC_REGULATORY_TYPE ...
export interface SEC_CFTC_REGULATORY_TYPE {
  isAppControlPrincipalFalseOmit: common.YES_NO_TYPE;
  isAppControlPrincipalViolation: common.YES_NO_TYPE;
  isApControlPrincipalCauseOfRestriction: common.YES_NO_TYPE;
  hasOrderAgainstAppPrincipal: common.YES_NO_TYPE;
  hasCivilMoneyPenalty: common.YES_NO_TYPE;
}

// FEDERAL_REGULATORY_TYPE ...
export interface FEDERAL_REGULATORY_TYPE {
  foundAppPrincipalFalseStatement: common.YES_NO_TYPE;
  foundAppPrincipalInViolation: common.YES_NO_TYPE;
  foundAppPrincipalCauseOfRestriction: common.YES_NO_TYPE;
  hasOrderAgainstAppPrincipal: common.YES_NO_TYPE;
  hasDeniedLicense: common.YES_NO_TYPE;
}

// SELF_REGULATORY_TYPE ...
export interface SELF_REGULATORY_TYPE {
  foundAppPrincipalFalseStatement: common.YES_NO_TYPE;
  foundAppPrincipalInViolation: common.YES_NO_TYPE;
  foundAppPrincipalCauseOfRestriction: common.YES_NO_TYPE;
  disciplinedAppPrincipalByExpelling: common.YES_NO_TYPE;
}

// PRINCIPAL_SANCTION_OPTION_TYPE ...
export interface PRINCIPAL_SANCTION_OPTION_TYPE {
  PRINCIPAL_SANCTION_RELIEF_BASE: PRINCIPAL_SANCTION_RELIEF_BASE;
  PRINCIPAL_SANCTION_TYPE: PRINCIPAL_SANCTION_TYPE;
}

// PRINCIPAL_SANCTION_OTHER_TYPE ...
export interface PRINCIPAL_SANCTION_OTHER_TYPE {
  sanctionOption: PRINCIPAL_SANCTION_OPTION_TYPE;
  otherSanctions: common.OTHER_TYPE;
}

// PRINCIPAL_SANCTION_OTHER_TYPE_2 ...
export interface PRINCIPAL_SANCTION_OTHER_TYPE_2 {
  OTHER_TYPE: common.OTHER_TYPE;
  PRINCIPAL_SANCTION_RELIEF_BASE: PRINCIPAL_SANCTION_RELIEF_BASE;
  PRINCIPAL_SANCTION_TYPE: PRINCIPAL_SANCTION_TYPE;
}

export type MATTER_RESOLVED_BASE = 'Consent' | 'Dismissed' | 'Settled';
export type MATTER_RESOLVED_TYPE =
  | 'Acceptance, Waiver & Consent (AWC)'
  | 'Decision & Order of Offer Settlement'
  | 'Decision'
  | 'Order'
  | 'Stipulation and Consent'
  | 'Vacated';
export type MATTER_RESOLVED_TYPE_2 = 'Judegement Rendered' | 'Opinion' | 'Withdrawn';
export type MATTER_RESOLVED_OTHER_TYPE = 'Withdrawn' | 'Other';
export type MATTER_RESOLVED_OPTION_TYPE = MATTER_RESOLVED_BASE | MATTER_RESOLVED_TYPE;

// MATTER_RESOLVED_OPTION_TYPE_4 ...
export type MATTER_RESOLVED_OPTION_TYPE_4 = MATTER_RESOLVED_BASE | MATTER_RESOLVED_TYPE;

// MATTER_RESOLVED_OPTION_TYPE_5 ...
export type MATTER_RESOLVED_OPTION_TYPE_5 = MATTER_RESOLVED_OPTION_TYPE_4 | MATTER_RESOLVED_OTHER_TYPE;

// REGULATORY_DRP_PART2_TYPE ...
export interface REGULATORY_DRP_PART2_TYPE {
  regulatorInitiatedOption: REGULATOR_INITIATED_OPTION_TYPE;
  fullNameRegulator: common.STRING_150_TYPE;
  principalSanction: PRINCIPAL_SANCTION_OTHER_TYPE;
  dateInitiated: EXACT_OR_EXPLANATION;
  docketOrCaseNo: common.STRING_25_TYPE;
  employingFirm: common.ENTITY_NAME_TYPE;
  principalProduct: PRINCIPAL_PRODUCT_TYPE;
  allegationsDescription: common.STRING_255_TYPE;
  currentStatus: EVENT_STATUS_TYPE;
  actionAppealedTo: APPEALED_TO_TYPE;
  matterResolvedType: MATTER_RESOLVED_OPTION_TYPE;
  resolutionDate: EXACT_OR_EXPLANATION;
  sanctionsOrdered: SANCTIONS_ORDERED_TYPE;
  summaryOfDetails: common.STRING_255_TYPE;
}

// REGULATORY_DRP_TYPE ...
export interface REGULATORY_DRP_TYPE {
  regulatoryDRPPart1: DRP_PART1_TYPE;
  regulatoryDRPPart2: REGULATORY_DRP_PART2_TYPE;
}

// REGULATORY_DRP_TYPES ...
export interface REGULATORY_DRP_TYPES {
  regulatoryDRP: Array<REGULATORY_DRP_TYPE>;
}

// REGULATORY_DISCLOSURE_TYPE ...
export interface REGULATORY_DISCLOSURE_TYPE {
  secOrCFTCRegulatory: SEC_CFTC_REGULATORY_TYPE;
  federalRegulatory: FEDERAL_REGULATORY_TYPE;
  selfRegulatory: SELF_REGULATORY_TYPE;
  hasAppPrincipalActAsAttorneyRevoked: common.YES_NO_TYPE;
  IsAppPrincipalSubjectRegulatoryProceeding: common.YES_NO_TYPE;
  regulatoryDisclosureDetails: REGULATORY_DRP_TYPES;
}

// MATTER_RESOLVED_OPTION_TYPE_2 ...
export interface MATTER_RESOLVED_OPTION_TYPE_2 {
  MATTER_RESOLVED_BASE: MATTER_RESOLVED_BASE;
  MATTER_RESOLVED_TYPE_2: MATTER_RESOLVED_TYPE_2;
}

// MATTER_RESOLVED_OPTION_TYPE_3 ...
export interface MATTER_RESOLVED_OPTION_TYPE_3 {
  matterResolvedType: MATTER_RESOLVED_OPTION_TYPE_2;
  other: common.OTHER_TYPE;
}

export type COURT_INITIATED_BY_OPTION_TYPE =
  | 'Regulator'
  | 'Foreign financial regulatory authority'
  | 'SRO'
  | 'Commodities exchange'
  | 'Agency'
  | 'Firm, private plaintiff';

export type PRINCIPAL_RELIEF_TYPE =
  | 'Civl Penalty(ies)/Fines)'
  | 'Money Damages (Private/Civil Complaint)'
  | 'Restraining Order';

// PRINCIPAL_RELIEF_OPTION_TYPE ...
export interface PRINCIPAL_RELIEF_OPTION_TYPE {
  PRINCIPAL_RELIEF_TYPE: PRINCIPAL_RELIEF_TYPE;
  PRINCIPAL_SANCTION_RELIEF_BASE: PRINCIPAL_SANCTION_RELIEF_BASE;
}

// PRINCIPAL_RELIEF_OTHER_TYPE ...
export interface PRINCIPAL_RELIEF_OTHER_TYPE {
  reliefOption: PRINCIPAL_RELIEF_OPTION_TYPE;
  otherReliefSought: common.OTHER_TYPE;
}

// COURT_INITIATED_BY_INFO_TYPE ...
export interface COURT_INITIATED_BY_INFO_TYPE {
  courtInitiatedByOption: COURT_INITIATED_BY_OPTION_TYPE;
  courtInitiatedByOther: common.OTHER_TYPE;
}

// CIVIL_JUDICIAL_DRP_PART2_TYPE ...
export interface CIVIL_JUDICIAL_DRP_PART2_TYPE {
  courtInitiatedBy: COURT_INITIATED_BY_INFO_TYPE;
  principalRelief: PRINCIPAL_RELIEF_OTHER_TYPE;
  filingDate: EXACT_OR_EXPLANATION;
  principalProduct: PRINCIPAL_PRODUCT_TYPE;
  formalActionBrought: CHARGES_WHERE_BROUGHT_IN;
  employingFirm: common.ENTITY_NAME_TYPE;
  allegationsDescription: common.STRING_255_TYPE;
  currentStatus: EVENT_STATUS_TYPE;
  actionAppealedTo: APPEALED_TO_TYPE;
  noticeDate: EXACT_OR_EXPLANATION;
  matterResolved: MATTER_RESOLVED_OPTION_TYPE_3;
  resolutionDate: EXACT_OR_EXPLANATION;
  resolutionDetail: SANCTIONS_ORDERED_TYPE;
  summaryOfDetails: common.STRING_255_TYPE;
}

// CIVIL_JUDICIAL_DRP_TYPE ...
export interface CIVIL_JUDICIAL_DRP_TYPE {
  civilJudicialDRPPart1: DRP_PART1_TYPE;
  civilJudicialDRPPart2: CIVIL_JUDICIAL_DRP_PART2_TYPE;
}

// CIVIL_JUDICIAL_DRP_TYPES ...
export interface CIVIL_JUDICIAL_DRP_TYPES {
  civilJudicialDRP: Array<CIVIL_JUDICIAL_DRP_TYPE>;
}

// CIVIL_JUDICIAL_DISCLOSURE_TYPE ...
export interface CIVIL_JUDICIAL_DISCLOSURE_TYPE {
  hasCourtEnjoinedAppPrincipal: common.YES_NO_TYPE;
  hasCourtFoundAppPrincipalViolation: common.YES_NO_TYPE;
  hasCourtDismissedAgainstAppPrincipal: common.YES_NO_TYPE;
  IsAppPrincipalSubjectCivilProceeding: common.YES_NO_TYPE;
  civilJudicialDisclosures: CIVIL_JUDICIAL_DRP_TYPES;
}

export type BANKRUPTCY_ACTION_OPTION_TYPE = 'Bankruptcy' | 'Declaration' | 'Receivership' | 'Compromise' | 'Liquidated';

export type BANKRUPTCY_DISPOSITION_OPTION_TYPE =
  | 'Direct Payment Procedure'
  | 'Dismissed'
  | 'Satisfied/Released'
  | 'Discharged'
  | 'Dissolved'
  | 'SIPA Trustee Appointed';

// BANKRUPTCY_ACTION_TYPE ...
export interface BANKRUPTCY_ACTION_TYPE {
  bankruptcyOption: BANKRUPTCY_ACTION_OPTION_TYPE;
  other: common.OTHER_TYPE;
}

// BANKRUPTCY_ACTION_TYPE_2 ...
export interface BANKRUPTCY_ACTION_TYPE_2 {
  bankruptcyOption: BANKRUPTCY_ACTION_OPTION_TYPE;
  other: common.OTHER_TYPE;
}

// BANKRUPTCY_DISPOSITION_TYPE ...
export interface BANKRUPTCY_DISPOSITION_TYPE {
  dispositionOptionType: BANKRUPTCY_DISPOSITION_OPTION_TYPE;
  other: common.OTHER_TYPE;
}

// SIPA_TRUSTEE_OR_PAYMENT ...
export interface SIPA_TRUSTEE_OR_PAYMENT {
  nameOfTrustee: common.ENTITY_NAME_TYPE;
  amountPaidOrAgreedTo: common.DECIMAL_TYPE14_2;
}

// SIPA_TRUSTEE_TYPE ...
export interface SIPA_TRUSTEE_TYPE {
  sipaTrusteeOrPayment: SIPA_TRUSTEE_OR_PAYMENT;
  isCurrentlyOpen: common.YES_NO_TYPE;
  dateDirectPayment: EXACT_OR_EXPLANATION;
}

// BANKRUPTCY_DRP_PART2_TYPE ...
export interface BANKRUPTCY_DRP_PART2_TYPE {
  actionType: BANKRUPTCY_ACTION_TYPE;
  actionDate: EXACT_OR_EXPLANATION;
  financialActionRelates: CHARGED_ORGANIZATION;
  courtActionBroughtIn: CHARGES_WHERE_BROUGHT_IN;
  isActionPending: common.YES_NO_TYPE;
  dispositionType: BANKRUPTCY_DISPOSITION_TYPE;
  dispositionDate: EXACT_OR_EXPLANATION;
  summaryOfEvents: common.STRING_255_TYPE;
  sipaTrustee: SIPA_TRUSTEE_TYPE;
  detailsOfDisposition: common.STRING_255_TYPE;
}

// BANKRUPTCY_DRP_TYPE ...
export interface BANKRUPTCY_DRP_TYPE {
  bankruptcyDRPPart1: DRP_PART1_TYPE;
  backruptcyDRPPart2: BANKRUPTCY_DRP_PART2_TYPE;
}

// BANKRUPTCY_DRP_TYPES ...
export interface BANKRUPTCY_DRP_TYPES {
  bankruptcyDRP: Array<BANKRUPTCY_DRP_TYPE>;
}

// PAYOUT_TYPE ...
export interface PAYOUT_TYPE {
  payoutAmount: common.DECIMAL_TYPE14_2;
  datePaid: common.DATE_TYPE;
}

// PAYOUT_TYPE_2 ...
export interface PAYOUT_TYPE_2 {
  payoutAmount: common.DECIMAL_TYPE14_2_FIXED;
  datePaid: common.DATE_TYPE;
}

// BOND_DRP_TYPE ...
export interface BOND_DRP_TYPE {
  applicantInfo: APPLICANT_INFO;
  firmName: common.ENTITY_NAME_TYPE;
  bondingCompanyName: common.ENTITY_NAME_TYPE;
  dispositionType: BOND_DISPOSITION_OPTION_TYPE;
  dispositoinDate: EXACT_OR_EXPLANATION;
  payoutInfo: PAYOUT_TYPE;
  summarizeDetails: common.STRING_255_TYPE;
}

// BOND_DRP_TYPES ...
export interface BOND_DRP_TYPES {
  bondDRP: Array<BOND_DRP_TYPE>;
}

// EVENT_PROCEED_NUMBERS ...
export interface EVENT_PROCEED_NUMBERS {
  eventOrProceedNum: common.STRING_NUMERIC_3_TYPE;
  eventOrProceedTotal: common.STRING_NUMERIC_3_TYPE;
}

// LIEN_TYPE ...
export enum LIEN_TYPE {
  civil = 'Civil',
  default = 'Default',
  tax = 'Tax',
}

// JUDGEMENT_DRP_TYPE ...
export interface JUDGEMENT_DRP_TYPE {
  applicantInfo: APPLICANT_INFO;
  eventProceedingNumbers: EVENT_PROCEED_NUMBERS;
  JudgementOrLienAmout: common.DECIMAL_TYPE14_2_FIXED;
  judgementOrLienHolder: common.STRING_150_TYPE;
  judegmentOrLienType: LIEN_TYPE;
  dateFiled: EXACT_OR_EXPLANATION;
  isJudgentLienOutstanding: common.TRUE_FALSE_TYPE;
  provideStatusDate: EXACT_OR_EXPLANATION;
  matterResolved: LIEN_RESOLVED_TYPE;
  court: CHARGES_WHERE_BROUGHT_IN;
  summaryOfEvents: common.STRING_255_TYPE;
}

// JUDGEMENT_DRP_TYPES ...
export interface JUDGEMENT_DRP_TYPES {
  judgementDRP: Array<JUDGEMENT_DRP_TYPE>;
}

// FINANCIAL_DISCLOSURE_PART1_TYPE ...
export interface FINANCIAL_DISCLOSURE_PART1_TYPE {
  hasSubjectOfBankruptcy: common.YES_NO_TYPE;
  hasTrusteeAppointed: common.YES_NO_TYPE;
  bankruptcyDisclosureDetails: BANKRUPTCY_DRP_TYPES;
}

// FINANCIAL_DISCLOSURE_PART2_TYPE ...
export interface FINANCIAL_DISCLOSURE_PART2_TYPE {
  hasBondDenied: common.YES_NO_TYPE;
  bondDisclosureDetails: BOND_DRP_TYPES;
}

// FINANCIAL_DISCLOSURE_PART3_TYPE ...
export interface FINANCIAL_DISCLOSURE_PART3_TYPE {
  doesAppHaveLiens: common.YES_NO_TYPE;
  judgementDisclosureDetails: JUDGEMENT_DRP_TYPES;
}

// FINANCIAL_DISCLOSURE_TYPE ...
export interface FINANCIAL_DISCLOSURE_TYPE {
  financialDisclosurePart1: FINANCIAL_DISCLOSURE_PART1_TYPE;
  financialDisclosurePart2: FINANCIAL_DISCLOSURE_PART2_TYPE;
  financialDisclosurePart3: FINANCIAL_DISCLOSURE_PART3_TYPE;
}

// DRP_INFO_TYPE ...
export interface DRP_INFO_TYPE {
  criminalDisclosure: CRIMINAL_DISCLOSURE_TYPE;
  regulatoryDisclosure: REGULATORY_DISCLOSURE_TYPE;
  civilJudicialDisclosure: CIVIL_JUDICIAL_DISCLOSURE_TYPE;
  financialDisclosure: FINANCIAL_DISCLOSURE_TYPE;
}
