// Code generated by xgen.

import * as common from './common';

import * as crowdfunding_drp from './crowdfunding_drp';

// CFPORTAL: Initial application of funding portal, CFPORTAL/A: Amendment to  registration,  including a successor registration, CFPORTAL-W: Withdrawal of the funding portals registration
export enum SUBMISSION_TYPE {
  CFPORTAL = 'CFPORTAL',
  'CFPORTAL/A' = 'CFPORTAL/A',
  'CFPORTAL-W' = 'CFPORTAL-W',
}

// LEGAL_NAME_CHANGE_TYPE ...
export enum LEGAL_NAME_CHANGE_TYPE {
  'Funding portal name(1A)' = 'Funding portal name(1A)',
  'Business name (1B)' = 'Business name (1B)',
}

// LEGAL_STATUS_FORM_TYPE ...
export enum LEGAL_STATUS_FORM_TYPE {
  Corporation = 'Corporation',
  'Sole Proprietorship' = 'Sole Proprietorship',
  Partnership = 'Partnership',
  'Limited Liability Company' = 'Limited Liability Company',
  'Other (Please Specify)' = 'Other (Please Specify)',
}

// PR_TYPE ...
export enum PR_TYPE {
  PR = 'PR',
}

//
//                 NA-less than 5%,
//                 A-5% but less than 10%,
//                 B-10% but less than 25%,
//                 C-25% but less than 50%,
//                 D-50% but less than 75%,
//                 E-75% or more,
//                 G - Other (general partner, trustee, or elected member)
export enum OWNERSHIP_CODE_TYPE {
  NA = 'NA',
  A = 'A',
  B = 'B',
  C = 'C',
  D = 'D',
  E = 'E',
  G = 'G',
}

// DE: Domestic Entity, FE: Foreign Entity,  NP: Natural Person
export enum ENTITY_TYPE {
  DE = 'DE',
  FE = 'FE',
  NP = 'NP',
}

// A: addition, D: deletion,  C: change in information about the same person
export enum AMENDMENT_TYPE {
  A = 'A',
  D = 'D',
  C = 'C',
}

//
// BO: one of applicant's branch offices or affiliates,
// TP: a third party unaffiliated recordkeeper,
// O: other
export enum BOOK_KEEPING_ENTITY_TYPE {
  BO = 'BO',
  TP = 'TP',
  O = 'O',
}

// These elements are part of the FILER_CREDENTIALS_TYPE group
export interface FILER_CREDENTIALS_TYPE {
  filerCik: string;
  filerCcc: common.CCC_TYPE;
}

// These elements are part of the PREV_NAMES_AND_WEBSITE_URLS_TYPE group
export interface PREV_NAMES_AND_WEBSITE_URLS_TYPE {
  prevNamesOfPortal: common.ENTITY_NAME_TYPE;
  prevWebSiteUrls: common.STRING_256_TYPE;
}

// These elements are part of the OTHER_NAMES_AND_WEBSITE_URLS_TYPE group
export interface OTHER_NAMES_AND_WEBSITE_URLS_TYPE {
  otherNamesUsedPortal: common.STRING_150_TYPE;
  webSiteOfPortal: common.STRING_256_TYPE;
}

// These elements are part of the PORTAL_CONTACT_TYPE group
export interface PORTAL_CONTACT_TYPE {
  portalContactPhone: common.PHONE_TYPE;
  portalContactFax: common.PHONE_TYPE;
  portalContactEmail: common.INTERNET_ADDRESS_TYPE;
}

// These elements are part of the FOREIGN_REGISTRATION_TYPE group
export interface FOREIGN_REGISTRATION_TYPE {
  foreignFinancialRegulatory: common.STRING_150_TYPE;
  registrationNumber: common.STRING_256_TYPE;
  country: common.NON_US_COUNTRY_CODES;
}

// These elements are part of the FILER_TYPE group
export interface FILER_TYPE {
  filerCredentials: FILER_CREDENTIALS_TYPE;
  fileNumber: common.FILE_NUMBER_TYPE;
}

// These elements are part of the FLAGS_TYPE group
export interface FLAGS_TYPE {
  confirmingCopyFlag: common.TRUE_FALSE_TYPE;
  returnCopyFlag: common.TRUE_FALSE_TYPE;
  overrideInternetFlag: common.TRUE_FALSE_TYPE;
}

// These elements are part of the CONTACT_TYPE group
export interface CONTACT_TYPE {
  contactName: common.NAME_TYPE_150;
  contactPhone: common.PHONE_TYPE;
  contactEmail: common.INTERNET_ADDRESS_TYPE;
}

// These elements are part of the NOTIFICATIONS_TYPE group
export interface NOTIFICATIONS_TYPE {
  notificationEmail: Array<common.INTERNET_ADDRESS_TYPE>;
}

// These elements are part of the ACQUIRED_HISTORY_DETAILS_TYPE group
export interface ACQUIRED_HISTORY_DETAILS_TYPE {
  acquiredFundingPortal: common.ENTITY_NAME_TYPE;
  acquiredPortalFileNumber: common.FILE_NUMBER_TYPE;
  acquiredDesc: common.STRING_4000_TYPE;
}

// These elements are part of the CRIMINAL_DISCLOSURE_TYPE group
export interface CRIMINAL_DISCLOSURE_TYPE {
  isConvictedOfFelony: common.YES_NO_TYPE;
  isChargedWithFelony: common.YES_NO_TYPE;
  isConvictedMisdemeanor: common.YES_NO_TYPE;
  isChargedMisdemeanor: common.YES_NO_TYPE;
}

// These elements are part of the REGULATORY_ACTION_DISCLOSURE_TYPE group
export interface REGULATORY_ACTION_DISCLOSURE_TYPE {
  isMadeFalseStatement: common.YES_NO_TYPE;
  isViolatedRegulation: common.YES_NO_TYPE;
  isCauseOfDenial: common.YES_NO_TYPE;
  isOrderAgainst: common.YES_NO_TYPE;
  isImposedPenalty: common.YES_NO_TYPE;
  isUnEthical: common.YES_NO_TYPE;
  isFoundInViolationOfRegulation: common.YES_NO_TYPE;
  isFoundInCauseOfDenial: common.YES_NO_TYPE;
  isOrderAgainstActivity: common.YES_NO_TYPE;
  isDeniedLicense: common.YES_NO_TYPE;
  isFoundMadeFalseStatement: common.YES_NO_TYPE;
  isFoundInViolationOfRules: common.YES_NO_TYPE;
  isFoundInCauseOfSuspension: common.YES_NO_TYPE;
  isDisciplined: common.YES_NO_TYPE;
  isAuthorizedToActAttorney: common.YES_NO_TYPE;
  isRegulatoryComplaint: common.YES_NO_TYPE;
}

// These elements are part of the CIVIL_JUDICIAL_ACTION_DISCLOSURE_TYPE group
export interface CIVIL_JUDICIAL_ACTION_DISCLOSURE_TYPE {
  isEnjoined: common.YES_NO_TYPE;
  isFoundInViolationOfRegulation: common.YES_NO_TYPE;
  isDismissed: common.YES_NO_TYPE;
  isNamedInCivilProceeding: common.YES_NO_TYPE;
}

// These elements are part of the FINANCIAL_DISCLOSURE_TYPE group
export interface FINANCIAL_DISCLOSURE_TYPE {
  hasSubjectOfBankruptcy: common.YES_NO_TYPE;
  hasTrusteeAppointed: common.YES_NO_TYPE;
  hasBondDenied: common.YES_NO_TYPE;
  doesAppHaveLiens: common.YES_NO_TYPE;
}

// These elements are part of the NON_SECURITIES_RELATED_BUSINESS_TYPE group
export interface NON_SECURITIES_RELATED_BUSINESS_TYPE {
  isEngagedInNonSecurities: common.YES_NO_TYPE;
  nonSecuritiesBusinessDesc: common.STRING_256_TYPE;
}

// These elements are part of the INVESTOR_FUNDS_CONTACTS_TYPE group
export interface INVESTOR_FUNDS_CONTACTS_TYPE {
  investorFundsContactName: common.NAME_TYPE_150;
  investorFundsAddress: common.ADDRESS_TYPE;
  investorFundsContactPhone: common.PHONE_TYPE;
}

// These elements are part of the FILER_INFO_TYPE group
export interface FILER_INFO_TYPE {
  filer: FILER_TYPE;
  liveTestFlag: common.LIVE_TEST_TYPE;
  flags: FLAGS_TYPE;
  contact: CONTACT_TYPE;
  notifications: NOTIFICATIONS_TYPE;
}

// These elements are part of the IDENTIFYING_INFORMATION_TYPE group
export interface IDENTIFYING_INFORMATION_TYPE {
  amendmentExplanation: common.STRING_1K_TYPE;
  nameOfPortal: common.ENTITY_NAME_TYPE;
  otherNamesAndWebsiteUrls: OTHER_NAMES_AND_WEBSITE_URLS_TYPE;
  irsEmployerIdNumber: common.TAX_ID_TYPE;
  legalNameChange: string;
  prevNamesAndWebsiteUrls: Array<PREV_NAMES_AND_WEBSITE_URLS_TYPE>;
  portalAddress: common.ADDRESS_TYPE;
  mailingAddressDifferent: common.TRUE_FALSE_TYPE;
  portalMailingAddress: common.ADDRESS_TYPE;
  otherOfficeLocationAddress: common.ADDRESS_TYPE;
  portalContact: PORTAL_CONTACT_TYPE;
  contactEmployeeName: common.INDIVIDUAL_NAME_TYPE;
  contactEmployeeTitle: common.STRING_256_TYPE;
  employeeContact: PORTAL_CONTACT_TYPE;
  fiscalYearEnd: common.MONTH_TYPE;
  anyPreviousRegistrations: common.YES_NO_TYPE;
  secFileNumbers: Array<common.FILE_NUMBER_TYPE>;
  anyForeignRegistrations: common.YES_NO_TYPE;
  foreignRegistrations: Array<FOREIGN_REGISTRATION_TYPE>;
}

// These elements are part of the FORM_OF_ORGANIZATION_TYPE group
export interface FORM_OF_ORGANIZATION_TYPE {
  legalStatusForm: string;
  legalStatusOtherDesc: common.STRING_256_TYPE;
  jurisdictionOrganization: string;
  dateIncorporation: common.DATE_TYPE;
}

// These elements are part of the SUCCESSIONS_TYPE group
export interface SUCCESSIONS_TYPE {
  isSucceedingBusiness: common.YES_NO_TYPE;
  acquiredHistoryDetails: Array<ACQUIRED_HISTORY_DETAILS_TYPE>;
}

// These elements are part of the CONTROL_RELATIONSHIPS_TYPE group
export interface CONTROL_RELATIONSHIPS_TYPE {
  fullLegalNames: Array<LEGAL_NAME_TYPE>;
}

// These elements are part of the LEGAL_NAME_TYPE group
export interface LEGAL_NAME_TYPE {
  fullLegalName: common.NAME_TYPE_150;
}

// These elements are part of the DISCLOSURE_INFORMATION_TYPE group
export interface DISCLOSURE_QUESTIONS {
  criminalDisclosure: CRIMINAL_DISCLOSURE_TYPE;
  regulatoryActionDisclosure: REGULATORY_ACTION_DISCLOSURE_TYPE;
  civilJudicialActionDisclosure: CIVIL_JUDICIAL_ACTION_DISCLOSURE_TYPE;
  financialDisclosure: FINANCIAL_DISCLOSURE_TYPE;
}

// These elements are part of the ESCROW_ARRANGEMENTS_TYPE group
export interface ESCROW_ARRANGEMENTS_TYPE {
  investorFundsContacts: Array<INVESTOR_FUNDS_CONTACTS_TYPE>;
  compensationDesc: common.STRING_10K_TYPE;
}

// These elements are part of the EXECUTION_TYPE group
export interface EXECUTION_TYPE {
  executionDate: common.DATE_TYPE;
  fullLegalNameFundingPortal: common.ENTITY_NAME_TYPE;
  personSignature: common.STRING_255_TYPE;
  personTitle: common.STRING_60_TYPE;
}

// ENTITY_OR_NATURAL_PERSON_TYPE ...
export interface ENTITY_OR_NATURAL_PERSON_TYPE {
  fullLegalName: common.NAME_TYPE_150;
  entityType: string;
  titleStatus: common.STRING_256_TYPE;
  dateOfTitleStatusAcquired: common.DATE_MM_YYYY_TYPE;
  ownershipCode: string;
  controlPerson: common.YES_NO_TYPE;
  pr: string;
  crdNumber: common.CRD_NUMBER_TYPE;
  irsTaxNumber: common.TAX_ID_TYPE;
  irsTaxEmployerIdNumber: common.TAX_ID_TYPE;
}

// AMEND_ENTITY_OR_NATURAL_PERSON_TYPE ...
export interface AMEND_ENTITY_OR_NATURAL_PERSON_TYPE {
  fullLegalName: common.NAME_TYPE_150;
  entityType: string;
  typeOfAmendment: string;
  titleStatus: common.STRING_256_TYPE;
  dateOfTitleStatusAcquired: common.DATE_MM_YYYY_TYPE;
  ownershipCode: string;
  controlPerson: common.YES_NO_TYPE;
  pr: string;
  crdNumber: common.CRD_NUMBER_TYPE;
  irsTaxNumber: common.TAX_ID_TYPE;
  irsTaxEmployerIdNumber: common.TAX_ID_TYPE;
}

// These elements are part of the SCHEDULE_A_TYPE group
export interface SCHEDULE_A_TYPE {
  entityOrNaturalPerson: Array<ENTITY_OR_NATURAL_PERSON_TYPE>;
}

// These elements are part of the SCHEDULE_B_TYPE group
export interface SCHEDULE_B_TYPE {
  amendEntityOrNaturalPerson: Array<AMEND_ENTITY_OR_NATURAL_PERSON_TYPE>;
}

// These elements are part of the SCHEDULE_C_TYPE group
export interface SCHEDULE_C_TYPE {
  agentName: common.NAME_TYPE_150;
  agentAddress: common.ADDRESS_TYPE;
  personSignature: common.STRING_150_TYPE;
  printedName: common.NAME_TYPE_150;
  personTitle: common.STRING_150_TYPE;
  signatureDate: common.DATE_TYPE;
}

// These elements are part of the SCHEDULE_D_TYPE group
export interface SCHEDULE_D_TYPE {
  dateBusinessCeasedWithdrawn: common.DATE_TYPE;
  bookKeepingDetails: Array<BOOK_KEEPING_DETAILS_TYPE>;
  isInvestigated: common.YES_NO_TYPE;
  investorInitiatedComplaint: common.YES_NO_TYPE;
  privateCivilLitigation: common.YES_NO_TYPE;
}

// These elements are part of the BOOK_KEEPING_TYPE group
export interface BOOK_KEEPING_DETAILS_TYPE {
  bookKeepingEntityName: common.ENTITY_NAME_TYPE;
  bookKeepingEntityAddress: common.ADDRESS_TYPE;
  bookKeepingEntityPhone: common.PHONE_TYPE;
  bookKeepingEntityFax: common.PHONE_TYPE;
  bookKeepingEntityType: string;
  isAddressPrivateResidence: common.YES_NO_TYPE;
  bookKeepingLocationDesc: common.STRING_256_TYPE;
}

// These elements are part of the HEADER_DATA_TYPE group
export interface HEADER_DATA {
  submissionType: string;
  filerInfo: FILER_INFO_TYPE;
}

// These elements are part of the FORM_DATA_TYPE group
export interface FORM_DATA {
  identifyingInformation: IDENTIFYING_INFORMATION_TYPE;
  formOfOrganization: FORM_OF_ORGANIZATION_TYPE;
  successions: SUCCESSIONS_TYPE;
  controlRelationships: CONTROL_RELATIONSHIPS_TYPE;
  disclosureAnswers: DISCLOSURE_QUESTIONS;
  nonSecuritiesRelatedBusiness: NON_SECURITIES_RELATED_BUSINESS_TYPE;
  escrowArrangements: ESCROW_ARRANGEMENTS_TYPE;
  execution: EXECUTION_TYPE;
  scheduleA: SCHEDULE_A_TYPE;
  scheduleB: SCHEDULE_B_TYPE;
  scheduleC: SCHEDULE_C_TYPE;
  scheduleD: SCHEDULE_D_TYPE;
  criminalDrpInfo: crowdfunding_drp.CRIMINAL_DISCLOSURE_CONTAINER;
  regulatoryDrpInfo: crowdfunding_drp.REGULATORY_DISCLOSURE_CONTAINER;
  civilJudicialDrpInfo: crowdfunding_drp.CIVIL_JUDICIAL_DISCLOSURE_CONTAINER;
  bankruptcySipcDrpInfo: crowdfunding_drp.BANKRUPTCY_DISCLOSURE_CONTAINER;
  bondDrpInfo: crowdfunding_drp.BOND_DISCLOSURE_CONTAINER;
  judgementDrpInfo: crowdfunding_drp.JUDGEMENT_DISCLOSURE_CONTAINER;
}

// EdgarSubmission ...
export interface EdgarSubmission {
  schemaVersion: string;
  headerData: HEADER_DATA;
  formData: FORM_DATA;
  documents: common.EDGAR_DOCUMENTS_TYPE;
}

export interface PortalFiling {
  edgarSubmission: EdgarSubmission;
}
