// Code generated by xgen. DO NOT EDIT.

import * as common from "./common";
import * as common_drp from "./common_drp";

// INITIAL_AMENDED_TYPE ...
export type INITIAL_AMENDED_TYPE = "INITIAL" | "AMENDED";

// DRP_FILE_FOR_TYPE ...
export type DRP_FILE_FOR_TYPE =
  | "Applicant"
  | "Applicant and one or more associated persons"
  | "One or more of applicant's associated persons";

// APPLICANT_DRP_REMOVAL_REASON_TYPE ...
export type APPLICANT_DRP_REMOVAL_REASON_TYPE =
  | "The applicant is registered or applying for registration and the event or proceeding was resolved in the applicant's favor."
  | "The DRP was filed in error.";

// ASSOCIATED_PERSON_TYPE ...
export type ASSOCIATED_PERSON_TYPE = "a firm" | "a natural person";

// ASSOCIATED_PERSON_REGISTERED_TYPE ...
export type ASSOCIATED_PERSON_REGISTERED_TYPE =
  | "The associated person is registered with the SEC"
  | "The associated person is not registered with the SEC";

// ASSOCIATED_PERSON_DRP_REMOVAL_REASON_INFO_TYPE ...
export interface ASSOCIATED_PERSON_DRP_REMOVAL_REASON_INFO_TYPE {
  drpRemoveReason: DRP_REMOVE_REASON_TYPE;
  explanation: string;
}

// DRP_REMOVE_REASON_TYPE ...
export type DRP_REMOVE_REASON_TYPE =
  | "The associated person(s) is (are) no longer associated with the applicant."
  | "The event or proceeding was resolved in the associated person's favor."
  | "The event or proceeding occurred more than ten years ago."
  | "The DRP was filed in error.";

// EVENT_STATUS_TYPE ...
export type EVENT_STATUS_TYPE = "Pending" | "On Appeal" | "Final";

// FELONY_MISDEMEANOR_TYPE ...
export type FELONY_MISDEMEANOR_TYPE = "Felony" | "Misdemeanor";

// ASSOCIATED_PERSON_DETAILS_TYPE ...
export interface ASSOCIATED_PERSON_DETAILS_TYPE {
  personType: ASSOCIATED_PERSON_TYPE;
  personRegistered: ASSOCIATED_PERSON_REGISTERED_TYPE;
  fullName: common.STRING_150_TYPE;
  crdNumber: common.CRD_NUMBER_TYPE;
}

// DRP_FILE_FOR_TYPE_2 ...
export type DRP_FILE_FOR_TYPE_2 =
  | "Applicant"
  | "Applicant and one or more control affiliate(s)"
  | "One or more of control affiliate(s)";

// PRINCIPAL_PRODUCT_TYPE ...
export type PRINCIPAL_PRODUCT_TYPE =
  | "Annuity(ies) - Fixed"
  | "Annuity(ies) - Variable"
  | "Money Market Fund(s)"
  | "CD(s)"
  | "Commodity Option(s)"
  | "Debt - Asset Backed"
  | "Debt - Corporate"
  | "Debt - Government"
  | "Debt - Municipal"
  | "Derivative(s)"
  | "Direct Investment(s) - DPP & LP Interest(s)"
  | "Equity - OTC"
  | "Equity Listed (Common & Preferred Stock)"
  | "Futures - Commodity"
  | "Futures - Financial"
  | "Index Option(s)"
  | "Insurance"
  | "Investment Contract(s)"
  | "Mutual Fund(s)"
  | "No Product"
  | "Options"
  | "Penny Stock(s)"
  | "Unit Investment Trust(s)"
  | "Other";

// CRIMINAL_EVENT_COURT_TYPE ...
export type CRIMINAL_EVENT_COURT_TYPE =
  | "Federal Court"
  | "Military Court"
  | "State Court"
  | "Foreign Court";

// CRIMINAL_DISPOSITION_OPTION_TYPE ...
export type CRIMINAL_DISPOSITION_OPTION_TYPE =
  | "Acquitted"
  | "Amended"
  | "Convicted"
  | "Deferred Adjudication"
  | "Dismissed"
  | "Found not guilty"
  | "Pled guilty"
  | "Pled nolo contendere"
  | "Pled not guilty"
  | "Pretrial diversion/intervention"
  | "Reduced"
  | "Appealed"
  | "Other";

// CRIMINAL_RESPONDING_TO_TYPE ...
export type CRIMINAL_RESPONDING_TO_TYPE = "5-A(1)" | "5-A(2)" | "5-B(1)" | "5-B(2)";

// CRIMINAL_RESPONDING_TO_TYPES ...
export interface CRIMINAL_RESPONDING_TO_TYPES {
  responseQuestion: string;
}

// APPEAL_TYPE ...
export type APPEAL_TYPE =
  | "Affirmed"
  | "Vacated & Returned For Further Action"
  | "Vacated / Final"
  | "Other";

// SENTENCE_DURATION_TYPE ...
export interface SENTENCE_DURATION_TYPE {
  days: string;
  months: string;
  years: string;
}

// CRIMINAL_DISCLOSURE_CONTAINER ...
export interface CRIMINAL_DISCLOSURE_CONTAINER {
  criminalDrp: Array<CRIMINAL_DRP_TYPE>;
}

// CRIMINAL_DRP_TYPE is These elements are part of the CRIMINAL_DRP_TYPE group
export interface CRIMINAL_DRP_TYPE {
  initialOrAmended: string;
  respondingTo: CRIMINAL_RESPONDING_TO_TYPES;
  drpFiledFor: string;
  applicant: CRIMINAL_APPLICANT_TYPE;
  associatedPerson: Array<CRIMINAL_ASSOCIATED_PERSON_TYPE>;
}

// CRIMINAL_APPLICANT_TYPE is These elements are part of the CRIMINAL_APPLICANT_INFORMATION_TYPE group
export interface CRIMINAL_APPLICANT_TYPE {
  drpRemovalReason: string;
  criminalDrpDetails: CRIMINAL_DRP_PART_2_TYPE;
  dispositionDisclosure: DISPOSITION_DISCLOSURE_TYPE;
  summaryOfCircumstances: common.STRING_10K_TYPE;
}

// CRIMINAL_ASSOCIATED_PERSON_TYPE is These elements are part of the CRIMINAL_ASSOCIATED_PERSON_TYPE group
export interface CRIMINAL_ASSOCIATED_PERSON_TYPE {
  associatedPersonDetails: ASSOCIATED_PERSON_DETAILS_TYPE;
  drpRemovalInfo: ASSOCIATED_PERSON_DRP_REMOVAL_REASON_INFO_TYPE;
  criminalDrpDetails: CRIMINAL_DRP_PART_2_TYPE;
  dispositionDisclosure: DISPOSITION_DISCLOSURE_TYPE;
  summaryOfCircumstances: common.STRING_10K_TYPE;
}

// CRIMINAL_DRP_PART_2_TYPE is These elements are part of the CRIMINAL_DRP_PART_2 group
export interface CRIMINAL_DRP_PART_2_TYPE {
  organizationName: common.ENTITY_NAME_TYPE;
  engagedInInvestmentRelatedBusiness: common.YES_NO_TYPE;
  descRelationshipWithApplicant: common.STRING_10K_TYPE;
  courtType: string;
  nameOfCourt: common.STRING_256_TYPE;
  courtAddress: common.ADDRESS_TYPE;
  docketOrCaseNumber: common.STRING_256_TYPE;
  dateFirstCharged: common_drp.EXACT_OR_EXPLANATION;
  criminalCharge: Array<CRIMINAL_CHARGE_TYPE>;
  anyChargeFelony: common.YES_NO_TYPE;
  eventCurrentStatus: string;
  eventStatusDate: common_drp.EXACT_OR_EXPLANATION;
}

// CRIMINAL_CHARGE_TYPE is These elements are part of the CRIMINAL_CHARGE_TYPE group
export interface CRIMINAL_CHARGE_TYPE {
  chargeDesc: common.STRING_10K_TYPE;
  numberOfCounts: common.STRING_NUMERIC_3_TYPE;
  felonyOrMisdemeanor: string;
  plea: common.STRING_10K_TYPE;
  investmentProductType: common.STRING_1K_TYPE;
}

// DISPOSITION_DISCLOSURE_TYPE is These elements are part of the DISPOSITION_DISC_DETAIL_TYPE group
export interface DISPOSITION_DISCLOSURE_TYPE {
  dispositionTypes: string;
  dispositionTypeOtherDesc: common.STRING_256_TYPE;
  appealTypes: string;
  appealTypeOtherDesc: common.STRING_256_TYPE;
  dispositionDate: common.DATE_TYPE;
  sentencePenalty: common.STRING_1K_TYPE;
  duration: SENTENCE_DURATION_TYPE;
  startDatePenalty: common.DATE_TYPE;
  penaltyFineAmount: common.DECIMAL_TYPE14_2_FIXED;
  datePaid: common.DATE_TYPE;
}

// REGULATORY_ASSOCIATED_PERSON_REMOVE_REASON_TYPE ...
export type REGULATORY_ASSOCIATED_PERSON_REMOVE_REASON_TYPE =
  | "The associated person(s) is (are) no longer associated with the applicant."
  | "The event or proceeding was resolved in the associated person's favor."
  | "The DRP was filed in error.";

// REGULATORY_RESPONDING_TO_TYPE ...
export type REGULATORY_RESPONDING_TO_TYPE =
  | "5-C(1)"
  | "5-C(2)"
  | "5-C(3)"
  | "5-C(4)"
  | "5-C(5)"
  | "5-D(1)"
  | "5-D(2)"
  | "5-D(3)"
  | "5-D(4)"
  | "5-D(5)"
  | "5-E(1)"
  | "5-E(2)"
  | "5-E(3)"
  | "5-E(4)"
  | "5-F"
  | "5-G";

// REGULATORY_RESPONDING_TO_TYPES ...
export interface REGULATORY_RESPONDING_TO_TYPES {
  responseQuestion: string;
}

// PORTAL_DRP_FILE_FOR_TYPE ...
export type PORTAL_DRP_FILE_FOR_TYPE =
  | "Applicant (the funding portal)"
  | "Applicant and one or more of the applicant's associated person(s)"
  | "One or more of applicant's associated person(s)";

// REGULATOR_INITIATED_OPTION_TYPE ...
export type REGULATOR_INITIATED_OPTION_TYPE =
  | "SEC"
  | "Foreign Authority"
  | "Other Federal Authority"
  | "State"
  | "SRO";

// PRINCIPAL_SANCTION_TYPE ...
export type PRINCIPAL_SANCTION_TYPE =
  | "Civil and Administrative Penalty(ies)/Fine(s)"
  | "Restitution"
  | "Bar"
  | "Cease and Desist"
  | "Censure"
  | "Denial"
  | "Expulsion"
  | "Revocation"
  | "Injunction"
  | "Prohibition"
  | "Reprimand"
  | "Disgorgement"
  | "Suspension"
  | "Undertaking"
  | "Other";

// REGULATORY_MATTER_RESOLVED_TYPE ...
export type REGULATORY_MATTER_RESOLVED_TYPE =
  | "Acceptance, Waiver  & Consent (AWC)"
  | "Consent"
  | "Decision"
  | "Decision  & Order of Offer of Settlement"
  | "Dismissed"
  | "Withdrawn"
  | "Settled"
  | "Stipulation  & Consent"
  | "Vacated"
  | "Order"
  | "Other";

// SANCTIONS_ORDERED_LIST_TYPE ...
export type SANCTIONS_ORDERED_LIST_TYPE =
  | "Monetary/Fine"
  | "Bar"
  | "Revocation/Expulsion/Denial"
  | "Disgorgement"
  | "Cease and Desist/ Injunction"
  | "Censure"
  | "Suspension";

// SANCTIONS_ORDERED_TYPE ...
export interface SANCTIONS_ORDERED_TYPE {
  sanctionOrdered: string;
}

// SANCTIONS_ORDERED_DETAIL_TYPE ...
export interface SANCTIONS_ORDERED_DETAIL_TYPE {
  sanctionsOrdered: SANCTIONS_ORDERED_TYPE;
  amountPaid: common.DECIMAL_TYPE14_2_FIXED;
  otherSanctions: common.STRING_10K_TYPE;
  sanctionDetail: common.STRING_10K_TYPE;
}

// REGULATORY_DISCLOSURE_CONTAINER ...
export interface REGULATORY_DISCLOSURE_CONTAINER {
  regulatoryDrp: Array<REGULATORY_DRP_TYPE>;
}

// REGULATORY_DRP_TYPE is These elements are part of the REGULATORY_ACTION_DRP_TYPE group
export interface REGULATORY_DRP_TYPE {
  initialOrAmended: string;
  respondingTo: REGULATORY_RESPONDING_TO_TYPES;
  drpFiledFor: string;
  applicant: REGULATORY_APPLICANT_INFORMATION_TYPE;
  associatedPerson: Array<REGULATORY_ASSOCIATED_PERSON_TYPE>;
}

// REGULATORY_APPLICANT_INFORMATION_TYPE is These elements are part of the REGULATORY_APPLICANT_INFORMATION_TYPE group
export interface REGULATORY_APPLICANT_INFORMATION_TYPE {
  drpRemovalReason: string;
  regulatoryDrpDetails: REGULATORY_DRP_PART_2_TYPE;
}

// REGULATORY_ASSOCIATED_PERSON_TYPE is These elements are part of the REGULATORY_ASSOCIATED_PERSON_TYPE group
export interface REGULATORY_ASSOCIATED_PERSON_TYPE {
  associatedPersonDetails: ASSOCIATED_PERSON_DETAILS_TYPE;
  drpRemovalReason: string;
  circumstancesExplanation: common.STRING_10K_TYPE;
  regulatoryDrpDetails: REGULATORY_DRP_PART_2_TYPE;
}

// REGULATORY_DRP_PART_2_TYPE is These elements are part of the REGULATORY_DRP_PART_2_TYPE group
export interface REGULATORY_DRP_PART_2_TYPE {
  regulatoryActionInitiatedBy: string;
  regulatorName: common.STRING_1K_TYPE;
  principalSanction: string;
  otherPrincipalSanctionDesc: common.STRING_1K_TYPE;
  otherSanctionsDesc: common.STRING_10K_TYPE;
  dateInitiated: common.EXACT_OR_EXPLANATION;
  docketOrCaseNumber: common.STRING_256_TYPE;
  apEmployingFirm: common.STRING_150_TYPE;
  principalProductType: string;
  principalProductTypeOtherDesc: common.STRING_256_TYPE;
  otherProductDesc: common.STRING_256_TYPE;
  descAllegations: common.STRING_10K_TYPE;
  currentStatus: string;
  appealedTo: common.STRING_256_TYPE;
  matterResolvedType: string;
  matterResolvedTypeOtherDesc: common.STRING_256_TYPE;
  resolutionDateExactExplain: common.EXACT_OR_EXPLANATION;
  sanctionsOrderedDetails: SANCTIONS_ORDERED_DETAIL_TYPE;
  summaryOfDetails: common.STRING_10K_TYPE;
}

// CIVIL_JUDICIAL_ASSOCIATED_PERSON_REMOVE_REASON_TYPE ...
export type CIVIL_JUDICIAL_ASSOCIATED_PERSON_REMOVE_REASON_TYPE =
  | "The associated person(s) is (are) no longer associated with the applicant"
  | "The event or proceeding was resolved in the associated person's favor"
  | "The DRP was filed in error";

// CIVIL_JUDICIAL_DISCLOSURE_CONTAINER ...
export interface CIVIL_JUDICIAL_DISCLOSURE_CONTAINER {
  civilJudicialDrp: Array<CIVIL_JUDICIAL_DRP_TYPE>;
}

// CIVIL_JUDICIAL_DRP_TYPE is These elements are part of the CIVIL_JUDICIAL_DRP_TYPE group
export interface CIVIL_JUDICIAL_DRP_TYPE {
  initialOrAmended: string;
  respondingTo: CIVIL_JUDICIAL_RESPONDING_TO_TYPES;
  drpFiledFor: string;
  applicant: CIVIL_JUDICIAL_APPLICANT_TYPE;
  associatedPerson: Array<CIVIL_JUDICIAL_ASSOCIATED_PERSON_TYPE>;
}

// CIVIL_JUDICIAL_RESPONDING_TO_TYPE ...
export type CIVIL_JUDICIAL_RESPONDING_TO_TYPE = "5-H(1)" | "5-H(2)" | "5-H(3)" | "5-I";

// CIVIL_JUDICIAL_RESPONDING_TO_TYPES ...
export interface CIVIL_JUDICIAL_RESPONDING_TO_TYPES {
  responseQuestion: string;
}

// CIVIL_JUDICIAL_APPLICANT_TYPE is These elements are part of the CIVIL_JUDICIAL_APPLICANT_TYPE group
export interface CIVIL_JUDICIAL_APPLICANT_TYPE {
  drpRemovalReason: string;
  circumstancesExplanation: common.STRING_10K_TYPE;
  civilJudicialDrpDetails: CIVIL_JUDICIAL_DRP_PART_2_TYPE;
}

// CIVIL_JUDICIAL_ASSOCIATED_PERSON_TYPE is These elements are part of the CIVIL_JUDICIAL_ASSOCIATED_PERSON_TYPE group
export interface CIVIL_JUDICIAL_ASSOCIATED_PERSON_TYPE {
  associatedPersonDetails: ASSOCIATED_PERSON_DETAILS_TYPE;
  drpRemovalReason: string;
  circumstancesExplanation: common.STRING_10K_TYPE;
  civilJudicialDrpDetails: CIVIL_JUDICIAL_DRP_PART_2_TYPE;
}

// CIVIL_JUDICIAL_DRP_PART_2_TYPE is These elements are part of the CIVIL_JUDICIAL_DRP_PART_2 group
export interface CIVIL_JUDICIAL_DRP_PART_2_TYPE {
  courtActionInitiatorName: common.STRING_1K_TYPE;
  principalReliefSought: string;
  otherPrincipleReliefSought: common.STRING_1K_TYPE;
  otherReliefSought: common.STRING_1K_TYPE;
  filingDateOfCourtActionExactOrExplain: common.EXACT_OR_EXPLANATION;
  principalProductType: string;
  otherPrincipalProductType: common.STRING_1K_TYPE;
  otherProductType: common.STRING_1K_TYPE;
  civilActionCourtType: string;
  civilActionCourtName: common.STRING_256_TYPE;
  cityOrCounty: common.STRING_150_TYPE;
  stateOrCountry: string;
  docketOrCaseNumber: common.STRING_256_TYPE;
  associatePersonEmployingFirm: common.STRING_150_TYPE;
  describeCivilActionAllegations: common.STRING_10K_TYPE;
  eventCurrentStatus: string;
  courtNameAndDateAppeal: common.STRING_1K_TYPE;
  processingDateCourtActionExactOrExplain: common.EXACT_OR_EXPLANATION;
  matterResolveType: string;
  otherMatterResolveType: common.STRING_256_TYPE;
  resolutionDateExactOrExplain: common.EXACT_OR_EXPLANATION;
  sanctionReliefType: SANCTIONS_ORDERED_TYPE;
  grantOrFineAmount: common.DECIMAL_TYPE14_2_FIXED;
  otherSanctionsOrdered: common.STRING_10K_TYPE;
  sanctionDetail: common.STRING_10K_TYPE;
  summaryOfCircumstances: common.STRING_10K_TYPE;
}

// RELIEF_SOUGHT_TYPE ...=
export type RELIEF_SOUGHT_TYPE =
  | "Cease and Desist"
  | "Restraining Order"
  | "Injunction"
  | "Disgorgement"
  | "Civil Penalty(ies)/Fine(s)"
  | "Restitution"
  | "Money Damages"
  | "Other";

// CIVIL_ACTION_COURT_TYPE ...
export enum CIVIL_ACTION_COURT_TYPE {
  "Federal Court" = "Federal Court",
  "State Court" = "State Court",
  "Foreign Court" = "Foreign Court",
}

// MATTER_RESOLVE_TYPE ...
export type MATTER_RESOLVE_TYPE =
  | "Consent"
  | "Judgement Rendered"
  | "Settled"
  | "Dismissed"
  | "Opinion"
  | "Withdrawn "
  | "Other";

// BANKRUPTCY_ACTION_TYPE ...
export type BANKRUPTCY_ACTION_TYPE =
  | "Bankruptcy"
  | "Compromise"
  | "Declaration"
  | "Liquidated"
  | "Receivership"
  | "Other";

// BANKRUPTCY_SIPC_RESPONDING_TO_TYPES ...
export interface BANKRUPTCY_SIPC_RESPONDING_TO_TYPES {
  responseQuestion: string;
}

// BANKRUPTCY_SIPC_RESPONDING_TO_TYPE ...
export type BANKRUPTCY_SIPC_RESPONDING_TO_TYPE = "5-J(1)" | "5-J(2)";

// BANKRUPTCY_DISPOSITION_TYPE ...
export type BANKRUPTCY_DISPOSITION_TYPE =
  | "Direct Payment Procedure"
  | "Discharged"
  | "Dismissed"
  | "Dissolved"
  | "Satisfied/Released"
  | "SIPA Trustee Appointed"
  | "Other";

// BANKRUPTCY_DISCLOSURE_CONTAINER ...
export interface BANKRUPTCY_DISCLOSURE_CONTAINER {
  bankruptcyDrp: Array<BANKRUPTCY_SIPC_DRP_TYPE>;
}

// BANKRUPTCY_SIPC_DRP_TYPE is These elements are part of the BANKRUPTCY_SIPC_DRP_TYPE group
export interface BANKRUPTCY_SIPC_DRP_TYPE {
  initialOrAmended: string;
  respondingTo: BANKRUPTCY_SIPC_RESPONDING_TO_TYPES;
  drpFiledFor: string;
  applicant: BANKRUPTCY_APPLICANT_TYPE;
  affiliatePerson: Array<BANKRUPTCY_AFFILIATE_PERSON_TYPE>;
}

// BANKRUPTCY_APPLICANT_TYPE is These elements are part of the BANKRUPTCY_APPLICANT_TYPE group
export interface BANKRUPTCY_APPLICANT_TYPE {
  appBankruptcySipcDrpDetails: BANKRUPTCY_SIPC_DRP_APPLICANT_TYPE;
}

// BANKRUPTCY_AFFILIATE_PERSON_TYPE ...
export interface BANKRUPTCY_AFFILIATE_PERSON_TYPE {
  affBankruptcySipcDrpDetails: BANKRUPTCY_SIPC_DRP_AFFILIATE_TYPE;
}

// BANKRUPTCY_SIPC_DRP_APPLICANT_TYPE is These elements are part of the BANKRUPTCY_SIPC_DRP_APPLICANT_TYPE group
export interface BANKRUPTCY_SIPC_DRP_APPLICANT_TYPE {
  actionType: string;
  actionTypeOtherDesc: common.STRING_1K_TYPE;
  actionDate: common.EXACT_OR_EXPLANATION;
  organizationName: common.STRING_1K_TYPE;
  nameOfCourt: common.STRING_256_TYPE;
  cityOrCounty: common.STRING_150_TYPE;
  stateOrCountry: string;
  docketOrCaseNo: common.STRING_256_TYPE;
  bankruptcyChapterNo: common.STRING_256_TYPE;
  isActionPending: common.YES_NO_TYPE;
  dispositionType: string;
  dispositionTypeOtherDesc: common.STRING_256_TYPE;
  dispositionDate: common.EXACT_OR_EXPLANATION;
  summaryOfEvents: common.STRING_1K_TYPE;
  amountPaid: common.DECIMAL_TYPE14_2_FIXED;
  nameOfTrustee: common.STRING_150_TYPE;
  isCurrentlyOpen: common.YES_NO_TYPE;
  dateDirectPayment: common.EXACT_OR_EXPLANATION;
  detailsOfDisposition: common.STRING_10K_TYPE;
}

// BANKRUPTCY_SIPC_DRP_AFFILIATE_TYPE is These elements are part of the BANKRUPTCY_SIPC_DRP_AFFILIATE_TYPE group
export interface BANKRUPTCY_SIPC_DRP_AFFILIATE_TYPE {
  apCrdNumber: common.CRD_NUMBER_TYPE;
  controlAffiliateType: string;
  isRegistered: common.YES_NO_TYPE;
  fullNameOfFirmOrPerson: common.STRING_150_TYPE;
  isAmendmentRemoveDrp: common.YES_NO_TYPE;
  isConAffRegisteredCrd: common.YES_NO_TYPE;
  actionType: string;
  actionTypeOtherDesc: common.STRING_1K_TYPE;
  actionDate: common.EXACT_OR_EXPLANATION;
  organizationName: common.STRING_1K_TYPE;
  nameOfCourt: common.STRING_256_TYPE;
  cityOrCounty: common.STRING_150_TYPE;
  stateOrCountry: string;
  docketOrCaseNo: common.STRING_256_TYPE;
  bankruptcyChapterNo: common.STRING_256_TYPE;
  isActionPending: common.YES_NO_TYPE;
  dispositionType: string;
  dispositionTypeOtherDesc: common.STRING_256_TYPE;
  dispositionDate: common.EXACT_OR_EXPLANATION;
  summaryOfEvents: common.STRING_1K_TYPE;
  amountPaid: common.DECIMAL_TYPE14_2_FIXED;
  nameOfTrustee: common.STRING_150_TYPE;
  isCurrentlyOpen: common.YES_NO_TYPE;
  dateDirectPayment: common.EXACT_OR_EXPLANATION;
  detailsOfDisposition: common.STRING_10K_TYPE;
}

// BOND_RESPONDING_TO_TYPE ...
export enum BOND_RESPONDING_TO_TYPE {
  "5-K" = "5-K",
}

// BOND_DISCLOSURE_CONTAINER ...
export interface BOND_DISCLOSURE_CONTAINER {
  bondDrp: Array<BOND_DRP_TYPE>;
}

// BOND_DRP_TYPE is These elements are part of the BOND_DRP_TYPE group
export interface BOND_DRP_TYPE {
  initialOrAmended: string;
  respondingTo: string;
  firmName: common.ENTITY_NAME_TYPE;
  bondingCompanyName: common.ENTITY_NAME_TYPE;
  dispositionType: common_drp.BOND_DISPOSITION_OPTION_TYPE;
  dispositionDate: common_drp.EXACT_OR_EXPLANATION;
  payoutInfo: common_drp.PAYOUT_TYPE_2;
  summarizeDetails: string;
}

// JUDGEMENT_RESPONDING_TO_TYPE ...
export enum JUDGEMENT_RESPONDING_TO_TYPE {
  "5-L" = "5-L",
}

// LIEN_JUDGEMENT_TYPE ...
export enum LIEN_JUDGEMENT_TYPE {
  Civil = "Civil",
  Default = "Default",
  Tax = "Tax",
}

// LIEN_JUDGEMENT_OUTSTANDING_TYPE ...
export interface LIEN_JUDGEMENT_OUTSTANDING_TYPE {
  isJudgementLienOutstanding: string;
  provideExplanationDesc: string;
  matterResolved: common_drp.LIEN_RESOLVED_TYPE;
}

// JUDGEMENT_DISCLOSURE_CONTAINER ...
export interface JUDGEMENT_DISCLOSURE_CONTAINER {
  judgementDrp: Array<JUDGEMENT_DRP_TYPE>;
}

// JUDGEMENT_DRP_TYPE is These elements are part of the JUDGEMENT_DRP_TYPE group
export interface JUDGEMENT_DRP_TYPE {
  initialOrAmended: string;
  respondingTo: string;
  judgementOrLienAmount: number;
  judgementOrLienHolder: string;
  judgementOrLienType: string;
  dateFiled: common.EXACT_OR_EXPLANATION;
  judgementLienOutstanding: LIEN_JUDGEMENT_OUTSTANDING_TYPE;
  nameOfCourt: common.STRING_256_TYPE;
  courtAddress: common.ADDRESS_TYPE;
  docketOrCaseNumber: common.STRING_256_TYPE;
  summaryOfEvents: common.STRING_10K_TYPE;
}
