#!/usr/bin/env bun
/**
 * @license
 * Copyright 2026 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Post-processes the machine-generated EDGAR type modules in `src/types/edgar/`
 * so they satisfy the project's "no TS `enum`" convention.
 *
 * The upstream generator (`xgen`, see the "Code generated by xgen" banner atop
 * each file) emits string `enum` declarations for XSD enumerations. This script
 * rewrites each `export enum Name { Member = "Member", ... }` into the
 * equivalent `as const` object plus a `keyof typeof` union type:
 *
 *   export const Name = { Member: "Member", ... } as const;
 *   export type Name = (typeof Name)[keyof typeof Name];
 *
 * The declaration-merged const + type preserves both the value namespace
 * (`Name.Member`) and the type (`Name`) that a real enum provided, so the
 * rewrite is transparent to consumers.
 *
 * It is idempotent: files with no `export enum` are left untouched, so it is
 * safe to re-run after regenerating the modules with `xgen`.
 *
 * Usage: `bun run gen:types`
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const EDGAR_TYPES_DIR = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "types",
  "edgar"
);

/** Matches a whole `export enum Name { ... }` block (enum bodies have no nested braces). */
const ENUM_BLOCK = /export enum (\S+) \{([\s\S]*?)\n\}/g;

/** Rewrites a single enum body line (`Member = "value",`) to an object entry (`Member: "value",`). */
function convertMemberLine(line: string): string {
  const match = line.match(/^(\s*)(.+?)\s*=\s*(.+?),?\s*$/);
  if (!match) return line; // blank line, comment, or otherwise not a member
  const [, indent, key, value] = match;
  return `${indent}${key}: ${value},`;
}

/** Rewrites every `export enum` block in `source` to the `as const` + `keyof typeof` form. */
export function convertEnumsToConst(source: string): string {
  return source.replace(ENUM_BLOCK, (_full, name: string, body: string) => {
    const members = body.split("\n").map(convertMemberLine).join("\n");
    return (
      `export const ${name} = {${members}\n} as const;\n` +
      `export type ${name} = (typeof ${name})[keyof typeof ${name}];`
    );
  });
}

function main(): void {
  if (!fs.existsSync(EDGAR_TYPES_DIR)) {
    throw new Error(`EDGAR types directory not found: ${EDGAR_TYPES_DIR}`);
  }

  const files = fs
    .readdirSync(EDGAR_TYPES_DIR)
    .filter((name) => name.endsWith(".ts"))
    .map((name) => path.join(EDGAR_TYPES_DIR, name));

  let changed = 0;
  for (const file of files) {
    const before = fs.readFileSync(file, "utf8");
    const after = convertEnumsToConst(before);
    if (after !== before) {
      fs.writeFileSync(file, after);
      changed += 1;
      console.log(`rewrote enums -> as const: ${path.relative(process.cwd(), file)}`);
    }
  }

  console.log(changed === 0 ? "no enums to rewrite" : `rewrote ${changed} file(s)`);
}

if (import.meta.main) {
  main();
}
