/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import { Static, Type } from "typebox";
import type { ITabularStorage } from "workglow";
import { createServiceToken } from "workglow";
import { TypeNullable } from "../../util/TypeBoxUtil";
import { TypeSecCik } from "../../util/TypeSecCik";

/**
 * Crowdfunding schema - represents crowdfunding entities
 */
export const CrowdfundingSchema = Type.Object({
  cik: TypeSecCik({ description: "Central Index Key (CIK) - unique identifier for entity" }),
  file_number: Type.String({
    maxLength: 32,
    description: "File number",
  }),
  filing_date: Type.String({
    format: "date",
    description: "Filing date",
  }),
  name: Type.String({
    maxLength: 140,
    description: "Entity name",
  }),
  legal_status: Type.String({
    maxLength: 50,
    description: "Legal status",
  }),
  state_jurisdiction: Type.String({
    maxLength: 2,
    description: "State jurisdiction code",
  }),
  date_incorporation: Type.String({
    format: "date",
    description: "Date of incorporation",
  }),
  url: Type.String({
    maxLength: 256,
    description: "Issuer website",
  }),
  portal_cik: TypeSecCik({ description: "Portal CIK" }),
  status: Type.String({
    maxLength: 32,
    description: "Offering lifecycle status (generated by determineStatus)",
  }),
  progress_update: TypeNullable(
    Type.String({
      maxLength: 256,
      description: "Latest C-U progress-update narrative",
    })
  ),
  nature_of_amendment: TypeNullable(
    Type.String({
      maxLength: 256,
      description: "Latest C/A nature-of-amendment narrative",
    })
  ),
});

export type Crowdfunding = Static<typeof CrowdfundingSchema>;

/**
 * Crowdfunding repository storage type and primary key definitions
 */
export const CrowdfundingPrimaryKeyNames = ["cik", "file_number"] as const;
export type CrowdfundingRepositoryStorage = ITabularStorage<
  typeof CrowdfundingSchema,
  typeof CrowdfundingPrimaryKeyNames,
  Crowdfunding
>;

/**
 * Dependency injection tokens for repositories
 */
export const CROWDFUNDING_REPOSITORY_TOKEN = createServiceToken<CrowdfundingRepositoryStorage>(
  "sec.storage.crowdfundingRepository"
);

/**
 * Crowdfunding Offerings schema - represents crowdfunding offerings
 */
export const CrowdfundingOfferingsSchema = Type.Object({
  cik: TypeSecCik({ description: "Central Index Key (CIK) - unique identifier for entity" }),
  file_number: Type.String({
    maxLength: 32,
    description: "File number",
  }),
  filing_date: Type.String({
    format: "date",
    description: "Filing date",
  }),
  compensation_amount_percent: TypeNullable(
    Type.Number({
      minimum: 0,
      maximum: 1,
      description: "Compensation amount percent (decimal format)",
    })
  ),
  financial_interest_percent: TypeNullable(
    Type.Number({
      minimum: 0,
      maximum: 1,
      description: "Financial interest percent (decimal format)",
    })
  ),
  compensation_amount_detail: TypeNullable(
    Type.String({
      description: "Compensation amount detail",
    })
  ),
  financial_interest_detail: TypeNullable(
    Type.String({
      description: "Financial interest detail",
    })
  ),
  security_offered_type: TypeNullable(
    Type.String({
      description: "Security offered type",
    })
  ),
  no_of_security_offered: TypeNullable(
    Type.Integer({
      minimum: 0,
      description: "Number of securities offered",
    })
  ),
  price: TypeNullable(
    Type.Number({
      minimum: 0,
      description: "Price",
    })
  ),
  price_determination_method: TypeNullable(
    Type.String({
      description: "Price determination method",
    })
  ),
  offering_amount: TypeNullable(
    Type.Number({
      minimum: 0,
      description: "Offering amount",
    })
  ),
  maximum_offering_amount: TypeNullable(
    Type.Number({
      minimum: 0,
      description: "Maximum offering amount",
    })
  ),
  over_subscription_accepted: TypeNullable(
    Type.String({
      maxLength: 3,
      description: "Over subscription accepted (YES/NO)",
    })
  ),
  deadline_date: TypeNullable(
    Type.String({
      format: "date",
      description: "Deadline date",
    })
  ),
});

export type CrowdfundingOfferings = Static<typeof CrowdfundingOfferingsSchema>;

/**
 * Crowdfunding Offerings repository storage type and primary key definitions
 */
export const CrowdfundingOfferingsPrimaryKeyNames = ["cik", "file_number", "filing_date"] as const;
export type CrowdfundingOfferingsRepositoryStorage = ITabularStorage<
  typeof CrowdfundingOfferingsSchema,
  typeof CrowdfundingOfferingsPrimaryKeyNames,
  CrowdfundingOfferings
>;

export const CROWDFUNDING_OFFERINGS_REPOSITORY_TOKEN =
  createServiceToken<CrowdfundingOfferingsRepositoryStorage>(
    "sec.storage.crowdfundingOfferingsRepository"
  );

/**
 * Crowdfunding Reports schema - represents crowdfunding reports
 */
export const CrowdfundingReportsSchema = Type.Object({
  cik: TypeSecCik({ description: "Central Index Key (CIK) - unique identifier for entity" }),
  file_number: Type.String({
    maxLength: 32,
    description: "File number",
  }),
  filing_date: Type.String({
    format: "date",
    description: "Filing date",
  }),
  disclosure_name: Type.String({
    maxLength: 50,
    description: "Disclosure name",
  }),
  disclosure_value: TypeNullable(
    Type.Number({
      // Deliberately unbounded below. Four of the eighteen Reg CF disclosures
      // are routinely negative — netIncome/taxPaid for both fiscal years — and
      // a Reg CF issuer is an early-stage company, so a loss is the common case
      // rather than the exception.
      //
      // A `minimum: 0` here emitted a CHECK constraint whose failure mode was a
      // PARTIAL write, not a clean rejection: the parent `crowdfunding` row
      // committed and looked healthy while the disclosure insert aborted at the
      // first negative value, dropping that field and every one after it. FAFCO
      // stored 15 of 18 disclosures that way, missing exactly the four above.
      //
      // rega_financial_data is the same name/value financial-disclosure table
      // for Reg A and has never carried such a bound.
      description: "Disclosure value (may be negative — e.g. net income, tax paid)",
    })
  ),
});

export type CrowdfundingReports = Static<typeof CrowdfundingReportsSchema>;

/**
 * Crowdfunding Reports repository storage type and primary key definitions
 */
export const CrowdfundingReportsPrimaryKeyNames = [
  "cik",
  "file_number",
  "filing_date",
  "disclosure_name",
] as const;
export type CrowdfundingReportsRepositoryStorage = ITabularStorage<
  typeof CrowdfundingReportsSchema,
  typeof CrowdfundingReportsPrimaryKeyNames,
  CrowdfundingReports
>;

export const CROWDFUNDING_REPORTS_REPOSITORY_TOKEN =
  createServiceToken<CrowdfundingReportsRepositoryStorage>(
    "sec.storage.crowdfundingReportsRepository"
  );
