/**
 * @license
 * Copyright 2025 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import { Static, Type } from "typebox";
import type { ITabularStorage } from "workglow";
import { createServiceToken } from "workglow";
import { TypeNullable } from "../../util/TypeBoxUtil";
import { TypeSecCik } from "../../util/TypeSecCik";

/**
 * Crowdfunding History schema - tracks changes to crowdfunding entity attributes over time
 */
export const CrowdfundingHistorySchema = Type.Object({
  cik: TypeSecCik({ description: "Central Index Key (CIK) - unique identifier for entity" }),
  valid_from: Type.String({
    format: "date-time",
    description: "When this version became valid",
  }),
  valid_to: TypeNullable(
    Type.String({
      format: "date-time",
      description: "When this version ceased to be valid (null = current)",
    })
  ),
  accession_number: Type.String({
    maxLength: 25,
    description:
      "Accession of the filing that produced this version. Part of the PK so " +
      "two snapshots for one CIK landing in the same wall-clock millisecond " +
      "(e.g. a batch re-process) get distinct rows instead of colliding on " +
      "(cik, valid_from) and silently dropping a history version.",
  }),
  file_number: Type.String({
    maxLength: 32,
    description: "File number",
  }),
  filing_date: Type.String({
    format: "date",
    description: "Filing date",
  }),
  name: TypeNullable(
    Type.String({
      maxLength: 140,
      description: "Entity name",
    })
  ),
  legal_status: TypeNullable(
    Type.String({
      maxLength: 50,
      description: "Legal status",
    })
  ),
  state_jurisdiction: TypeNullable(
    Type.String({
      maxLength: 2,
      description: "State jurisdiction code",
    })
  ),
  date_incorporation: TypeNullable(
    Type.String({
      format: "date",
      description: "Date of incorporation",
    })
  ),
  url: TypeNullable(
    Type.String({
      maxLength: 256,
      description: "Issuer website",
    })
  ),
  portal_cik: TypeNullable(TypeSecCik({ description: "Portal CIK" })),
  status: TypeNullable(
    Type.String({
      maxLength: 32,
      description: "Offering lifecycle status (generated by determineStatus)",
    })
  ),
  progress_update: TypeNullable(
    Type.String({
      maxLength: 256,
      description: "Latest C-U progress-update narrative",
    })
  ),
  nature_of_amendment: TypeNullable(
    Type.String({
      maxLength: 256,
      description: "Latest C/A nature-of-amendment narrative",
    })
  ),
  change_source: Type.String({
    description: "Source of this change (e.g., 'Form C', 'SUBMISSION_UPDATE')",
  }),
  change_date: Type.String({
    format: "date-time",
    description: "When this change was recorded in our system",
  }),
});

export type CrowdfundingHistory = Static<typeof CrowdfundingHistorySchema>;

/**
 * Crowdfunding History repository storage type and primary key definitions
 */
export const CrowdfundingHistoryPrimaryKeyNames = [
  "cik",
  "valid_from",
  "accession_number",
] as const;
export type CrowdfundingHistoryRepositoryStorage = ITabularStorage<
  typeof CrowdfundingHistorySchema,
  typeof CrowdfundingHistoryPrimaryKeyNames,
  CrowdfundingHistory
>;

/**
 * Dependency injection tokens for repositories
 */
export const CROWDFUNDING_HISTORY_REPOSITORY_TOKEN =
  createServiceToken<CrowdfundingHistoryRepositoryStorage>(
    "sec.storage.crowdfundingHistoryRepository"
  );
