/**
 * @license
 * Copyright 2026 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import { Static, Type } from "typebox";
import { CIK_TYPE, ENTITY_NAME_TYPE, SCHEMA_VERSION_TYPE } from "../FormSchemaUtil";

/**
 * Form QUALIF — the SEC's notice that a Reg A offering statement has been
 * QUALIFIED.
 *
 * Unlike every other form here it is generated by the Commission, not the
 * filer, which is what makes it worth parsing: it is the authoritative
 * qualification date. The issuer-reported `offeringQualificationDate` on a 1-K
 * or 1-Z is a filer's recollection of the same event, and it is present on only
 * ~9% of offering-history rows. QUALIF covers 3,062 filings across 1,383
 * issuers.
 *
 * The document is small and machine-generated, so the shape is stable:
 *
 *   <edgarSubmission>
 *     <submissionType>QUALIF</submissionType>
 *     <effectiveData>
 *       <finalEffectivenessDispDate>2026-08-13</finalEffectivenessDispDate>
 *       <finalEffectivenessDispTime>16:00:00</finalEffectivenessDispTime>
 *       <form>1-A POS</form>
 *       <filer><cik/><entityName/><fileNumber/></filer>
 *     </effectiveData>
 *   </edgarSubmission>
 *
 * `form` names WHICH filing was qualified — an original 1-A, an amendment, or a
 * post-qualification amendment (1-A POS) — so one offering accumulates several
 * QUALIF notices over its life, one per qualified amendment.
 */

const DATE_TYPE = Type.String({ minLength: 1, maxLength: 20 });
const TIME_TYPE = Type.String({ minLength: 1, maxLength: 20 });
const FILE_NUMBER_TYPE = Type.String({ minLength: 1, maxLength: 17 });

const QUALIF_FILER_TYPE = Type.Object({
  cik: CIK_TYPE,
  entityName: Type.Optional(ENTITY_NAME_TYPE),
  fileNumber: Type.Optional(FILE_NUMBER_TYPE),
});

const EFFECTIVE_DATA_TYPE = Type.Object({
  finalEffectivenessDispDate: Type.Optional(DATE_TYPE),
  finalEffectivenessDispTime: Type.Optional(TIME_TYPE),
  // The form that was qualified ("1-A", "1-A/A", "1-A POS"). Optional because a
  // machine-generated document is not a guarantee: parse what is there rather
  // than failing a filing over a field the notice happened to omit.
  form: Type.Optional(Type.String({ maxLength: 32 })),
  filer: Type.Optional(QUALIF_FILER_TYPE),
});

export const FormQualifSchema = Type.Object({
  schemaVersion: Type.Optional(SCHEMA_VERSION_TYPE),
  submissionType: Type.Optional(Type.String({ maxLength: 32 })),
  act: Type.Optional(Type.String({ maxLength: 8 })),
  testOrLive: Type.Optional(Type.String({ maxLength: 8 })),
  effectiveData: Type.Optional(EFFECTIVE_DATA_TYPE),
});

export type FormQualif = Static<typeof FormQualifSchema>;

export const FormQualifSubmissionSchema = Type.Object({
  edgarSubmission: FormQualifSchema,
});

export type FormQualifSubmission = Static<typeof FormQualifSubmissionSchema>;
