/**
 * @license
 * Copyright 2026 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import { beforeEach, describe, expect, it } from "vitest";
import { resetDependencyInjectionsForTesting } from "../../../config/TestingDI";
import { setupAllDatabases } from "../../../config/setupAllDatabases";
import { RegAOfferingRepo } from "../../../storage/reg-a/RegAOfferingRepo";
import { Form_QUALIF } from "./Form_QUALIF";
import { processFormQualif } from "./Form_QUALIF.storage";

/**
 * Verbatim from EDGAR — `9999999997-26-000153`, UNLOCKD Inc's 2026-08-13
 * qualification. Machine-generated by the Commission, so this shape is the
 * shape, not one filer's rendering of it.
 */
const QUALIF_XML = `<?xml version="1.0"?>
<edgarSubmission>
    <schemaVersion>X0101</schemaVersion>
    <submissionType>QUALIF</submissionType>
    <act>33</act>
    <testOrLive>LIVE</testOrLive>
    <effectiveData>
        <finalEffectivenessDispDate>2026-08-13</finalEffectivenessDispDate>
        <finalEffectivenessDispTime>16:00:00</finalEffectivenessDispTime>
        <form>1-A POS</form>
        <filer>
            <cik>0001395005</cik>
            <entityName>UNLOCKD, Inc.</entityName>
            <fileNumber>024-12783</fileNumber>
        </filer>
    </effectiveData>
</edgarSubmission>`;

describe("Form_QUALIF parse", () => {
  it("reads the qualification date, qualified form and filer", async () => {
    const parsed = await Form_QUALIF.parse("QUALIF", QUALIF_XML);
    expect(parsed.submissionType).toBe("QUALIF");
    expect(parsed.effectiveData?.finalEffectivenessDispDate).toBe("2026-08-13");
    // Which filing was qualified — an offering accumulates several of these,
    // one per qualified amendment, which is why the notice names the form.
    expect(parsed.effectiveData?.form).toBe("1-A POS");
    expect(parsed.effectiveData?.filer?.fileNumber).toBe("024-12783");
    expect(parsed.effectiveData?.filer?.entityName).toBe("UNLOCKD, Inc.");
  });

  it("rejects a form it does not handle", async () => {
    await expect(Form_QUALIF.parse("1-A" as never, QUALIF_XML)).rejects.toThrow(/Invalid form/);
  });
});

describe("Form_QUALIF storage", () => {
  let repo: RegAOfferingRepo;

  beforeEach(async () => {
    resetDependencyInjectionsForTesting();
    await setupAllDatabases();
    repo = new RegAOfferingRepo();
  });

  it("records the qualification date against the issuer's file number", async () => {
    const parsed = await Form_QUALIF.parse("QUALIF", QUALIF_XML);
    await processFormQualif({
      // EDGAR files QUALIF under a Commission accession, so the filing CIK is
      // not the issuer's — the notice's own <filer><cik> is, and must win.
      cik: 9999999997,
      accession_number: "9999999997-26-000153",
      filing_date: "2026-08-13",
      formQualif: parsed,
    });

    const rows = await repo.getOfferingHistoriesByFileNumber("024-12783");
    expect(rows).toHaveLength(1);
    expect(rows[0].cik).toBe(1395005);
    expect(rows[0].qualification_date).toBe("2026-08-13");
  });

  it("stores nothing when the notice carries no file number", async () => {
    // Real but unusable: there is no offering to attach it to, and inventing a
    // key would put the qualification on the wrong offering.
    const parsed = await Form_QUALIF.parse(
      "QUALIF",
      QUALIF_XML.replace("<fileNumber>024-12783</fileNumber>", "")
    );
    await processFormQualif({
      cik: 1395005,
      accession_number: "9999999997-26-000154",
      filing_date: "2026-08-13",
      formQualif: parsed,
    });
    expect(await repo.getOfferingHistoriesByFileNumber("024-12783")).toHaveLength(0);
  });

  it("is idempotent — a replay upserts rather than duplicating", async () => {
    const parsed = await Form_QUALIF.parse("QUALIF", QUALIF_XML);
    const args = {
      cik: 9999999997,
      accession_number: "9999999997-26-000153",
      filing_date: "2026-08-13",
      formQualif: parsed,
    };
    await processFormQualif(args);
    await processFormQualif(args);
    expect(await repo.getOfferingHistoriesByFileNumber("024-12783")).toHaveLength(1);
  });
});
