/**
 * @license
 * Copyright 2026 Steven Roussey <sroussey@gmail.com>
 * SPDX-License-Identifier: Apache-2.0
 */

import * as cheerio from "cheerio";
import { parseNumeric } from "../../html/parseNumeric";

/**
 * Deterministic extraction of the financial statements from a Reg A annual
 * (1-K PART II) or semiannual (1-SA) report.
 *
 * No AI. Reg A carries no XBRL — all 28,041 filings across every Reg A form are
 * untagged, because Reg A issuers are exempt from tagging — so the statements
 * exist only as HTML tables. But those tables are machine-generated by filer
 * agents from accounting software, and their shape is consequently regular in a
 * way prospectus prose is not: a label column, then one numeric column per
 * period, with the period dates in a header row above.
 *
 * The parse is anchored on ACCOUNTING VOCABULARY rather than on document
 * structure — "Total Assets" identifies a balance sheet whatever the filer named
 * the file or however deeply the table is nested. That matters because the
 * filenames alone (`sixdbytes_1k.htm`, `ea0274451-1k_figpub.htm`,
 * `reig_1k-123125.htm`) show there is no naming convention to rely on.
 */

export const REGA_STATEMENT_KINDS = [
  "balance_sheet",
  "operations",
  "cash_flows",
  "stockholders_equity",
] as const;

export type RegAStatementKind = (typeof REGA_STATEMENT_KINDS)[number];

export interface RegAStatementRow {
  /** The line item exactly as the filer labelled it. */
  readonly label: string;
  /** One entry per period, index-aligned with {@link RegAStatement.periods}. */
  readonly values: (number | null)[];
}

export interface RegAStatement {
  readonly kind: RegAStatementKind;
  /**
   * The column headings as printed, in column order — whatever they say.
   *
   * Usually periods, but not always: a multi-series issuer heads its columns by
   * SEGMENT (`ROCF II Series`, `Eliminations`, `Consolidated`). Those labels are
   * the only thing distinguishing six columns of figures, so they are kept even
   * though they are not dates.
   */
  readonly columns: string[];
  /**
   * The subset of {@link columns} that read as reporting periods, in column
   * order — empty when the statement heads its columns by something else, or
   * states its date in a caption outside the table.
   */
  readonly periods: string[];
  readonly rows: RegAStatementRow[];
  /** True when the statement declares itself unaudited — 1-SA always does. */
  readonly unaudited: boolean;
}

/**
 * Vocabulary that identifies each statement. Every predicate needs TWO
 * independent anchors: a table mentioning "Net loss" alone is as likely to be a
 * note or an MD&A summary as a statement of operations, and a single anchor
 * pulls those in.
 */
const STATEMENT_ANCHORS: ReadonlyArray<{
  readonly kind: RegAStatementKind;
  readonly all: readonly RegExp[];
}> = [
  {
    kind: "balance_sheet",
    all: [/total\s+assets/i, /total\s+liabilities|liabilities\s+and\s+(share|stock)holders/i],
  },
  {
    kind: "cash_flows",
    // Checked before operations: a cash-flow statement also carries "net
    // income", so the more specific pair has to win.
    all: [/operating\s+activities/i, /financing\s+activities/i],
  },
  {
    kind: "operations",
    all: [/net\s+(income|loss)/i, /revenue|operating\s+expense|cost\s+of\s+(goods|revenue)/i],
  },
  {
    kind: "stockholders_equity",
    all: [/(share|stock)holders.{0,3}\s*(equity|deficit)/i, /balance\s*(,|\s+at|\s+as)/i],
  },
];

/** Rows whose label is a section heading rather than a line item. */
const SECTION_HEADING =
  /^(assets|liabilities|current assets|current liabilities|equity|revenues?|operating expenses|expenses)$/i;

const cellText = (raw: string): string => raw.replace(/ /g, " ").replace(/\s+/g, " ").trim();

/**
 * Reads the numeric values out of a row's cells.
 *
 * The cells are JOINED before matching, which is the whole reason this is not a
 * per-cell `parseNumeric` loop: EDGAR splits an accounting negative across cell
 * boundaries — `Net Income (Loss)` arrives as `['(1,349,427', ')']`. Parsed cell
 * by cell that reads as a POSITIVE 1,349,427, silently flipping the sign of
 * every loss in the corpus. Joining restores `(1,349,427)` before it is parsed.
 */
export function readRowValues(cellsAfterLabel: readonly string[]): number[] {
  const joined = cellsAfterLabel.join(" ").replace(/\s+/g, " ").trim();
  if (joined === "") return [];
  // Parenthesised first so `(1,234)` is taken whole rather than as a bare 1,234.
  const tokens = joined.match(VALUE_TOKEN);
  if (!tokens) return [];
  const out: number[] = [];
  for (const token of tokens) {
    // A statement prints a zero as a dash. Reading it as "no value" does not
    // just lose that cell — it SHIFTS every later column left, so a row of
    // `-  5,000` reports 5,000 under the first period instead of the second.
    if (DASH_PLACEHOLDER.test(token)) {
      out.push(0);
      continue;
    }
    // Whitespace is stripped before parsing, and that is load-bearing rather
    // than tidiness: `parseNumeric("$ (1,234)")` returns a POSITIVE 1,234 —
    // the space between the currency symbol and the parenthesis defeats its
    // negative detection — while `parseNumeric("$(1,234)")` returns -1,234.
    const value = parseNumeric(token.replace(/\s+/g, ""));
    if (value !== undefined) out.push(value);
  }
  return out;
}

/**
 * One value in a statement row: a parenthesised negative, a number, or a dash
 * standing in for zero. The dash alternative is last and requires the dash to
 * be free of adjacent digits, so it cannot bite into `-1,234` or a decimal.
 */
const VALUE_TOKEN =
  /\(\s*\$?\s*[\d,]+(?:\.\d+)?\s*\)|\$?\s*-?[\d,]+(?:\.\d+)?|(?<![\d.,])[-‒-―](?![\d.,])/g;

const DASH_PLACEHOLDER = /^[-‒-―]$/;

/** A cell that reads as a reporting period ("April 30, 2026", "December 31, 2025"). */
const PERIOD =
  /\b(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},?\s*\d{4}\b/;

/** A cell holding nothing but a year — how an operations statement heads its columns. */
const BARE_YEAR = /^(?:19|20)\d{2}$/;

/**
 * A month-and-day with NO year — the top half of a header split across two
 * ROWS:
 *
 * ```
 *            June 30,      December 31,
 *            2024          2023
 * ```
 *
 * Neither row is a date on its own, so joining cells within a row (which is
 * what {@link readDates} does) finds nothing. Worse, the `31` of
 * "December 31," reads as a figure, which would take the row for DATA and end
 * the header block before it began — leaving `June 30,` and `2024` as line
 * items with values.
 */
const MONTH_DAY =
  /^(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},?$/;

/** The month-day fragments of a split header row, in column order. */
const readMonthDays = (texts: readonly string[]): string[] =>
  texts.filter((c) => MONTH_DAY.test(c));

/**
 * Reads the dates out of one header row.
 *
 * The cells are JOINED first, for the same reason {@link readRowValues} joins
 * them: filers split a heading across cell boundaries, and GolfSuites heads its
 * columns `['June', '30,', '2023', '', 'December', '31,', '2022']` — per cell
 * that is no date at all. Joining recovers both.
 *
 * Safe against a share-count label restating dates in prose ("...as of April 30,
 * 2026 and October 31, 2025") because the caller only ever passes rows from the
 * header block, which ends at the first row carrying figures.
 */
function readDates(texts: readonly string[]): string[] {
  const joined = texts.join(" ").replace(/\s+/g, " ");
  return joined.match(new RegExp(PERIOD.source, "g")) ?? [];
}

/**
 * Reads the period headings from the rows above the data.
 *
 * Two shapes, because filers head the two statements differently. A balance
 * sheet prints full dates in the header row ("April 30, 2026"); a statement of
 * operations prints bare years ("2026", "2025") and puts the period language
 * ("For the Six Months Ended April 30,") in a caption OUTSIDE the table, where a
 * table-scoped parse cannot see it. Accepting only full dates left every
 * operations and cash-flow statement with no periods at all.
 *
 * The search stops at the first DATA row. A statement body is full of years — in
 * share-count labels, in note references — and scanning past the header would
 * pick those up as columns.
 */
function readHeader(rows: string[][]): { columns: string[]; periods: string[] } {
  // Collect the whole header BLOCK rather than stopping at the first row that
  // looks like one. Filers routinely split a heading over two rows — "As of" /
  // "For the Year Ended" on the first, the dates themselves on the second — so
  // returning at the first match yielded `["As of", "As of"]` and threw the
  // dates away.
  const header: string[][] = [];
  for (const cells of rows) {
    const texts = cells.map(cellText);
    const labelIndex = texts.findIndex((c) => c !== "");
    if (labelIndex !== -1) {
      // A row carrying a date is a heading however many digits it contains.
      // Without this the check reads "April 30, 2026" as the values 30 and 2026
      // and calls the header row data, ending the block before it starts.
      const isDataRow =
        readDates(texts).length === 0 &&
        readMonthDays(texts).length === 0 &&
        !BARE_YEAR.test(texts[labelIndex]) &&
        readRowValues(texts.slice(labelIndex + 1)).length > 0;
      if (isDataRow) break;
    }
    header.push(texts);
  }

  // Full dates win wherever in the block they sit: "April 30, 2026" says more
  // than "2026", which says more than "As of".
  for (const texts of header) {
    const dates = readDates(texts);
    if (dates.length >= 1) return { columns: dates, periods: dates };
  }

  // A header split across two rows: month-and-day on one, the years beneath.
  // Paired POSITIONALLY — the Nth month-day belongs to the Nth year — which is
  // what the columns mean; zipping them in any other order invents periods.
  for (let i = 0; i < header.length; i++) {
    const monthDays = readMonthDays(header[i]);
    if (monthDays.length === 0) continue;
    for (let j = i + 1; j < header.length; j++) {
      const years = header[j].filter((c) => BARE_YEAR.test(c));
      if (years.length === 0) continue;
      // Only pair when the two halves line up. A mismatch means the rows are
      // not two halves of one heading, and guessing would attach a year to the
      // wrong column.
      if (years.length !== monthDays.length) break;
      const paired = monthDays.map((d, k) => `${d.replace(/,$/, "")}, ${years[k]}`);
      return { columns: paired, periods: paired };
    }
  }

  for (const texts of header) {
    const years = texts.filter((c) => BARE_YEAR.test(c));
    if (years.length >= 2) return { columns: years, periods: years };
  }

  // No dates anywhere in the block: the columns are headed by something else. A
  // multi-series issuer heads them by SEGMENT (`ROCF II Series`, `Consolidated`)
  // and an equity statement by COMPONENT (`Par Value`, `APIC`) — labels that are
  // all that separates six columns of figures, so dropping them leaves the
  // values unattributable.
  //
  // The most DISTINCT row wins: a spanning "As of / As of" line carries one
  // distinct value however many cells it fills, so it loses to the row actually
  // naming the columns. Requiring the LABEL cell to be empty keeps this off a
  // section heading — `['ASSETS', '', '']` labels the rows beneath it, while a
  // column header starts empty — and the two-column floor rules out a stray cell.
  let best: string[] = [];
  let bestDistinct = 1;
  for (const texts of header) {
    const filled = texts.filter((c) => c !== "");
    const labelIndex = texts.findIndex((c) => c !== "");
    if (labelIndex <= 0 || filled.length < 2) continue;
    const distinct = new Set(filled).size;
    if (distinct > bestDistinct) {
      best = filled;
      bestDistinct = distinct;
    }
  }
  return { columns: best, periods: [] };
}

function classify(tableText: string): RegAStatementKind | null {
  for (const { kind, all } of STATEMENT_ANCHORS) {
    if (all.every((re) => re.test(tableText))) return kind;
  }
  return null;
}

/**
 * Extracts every financial statement it can identify from a Reg A report.
 *
 * Returns at most one statement per kind: a filing repeats its statements in the
 * table of contents and often again in the notes, so the candidate with the most
 * data rows wins. That is a better discriminator than document order — the
 * contents listing appears first and has no figures at all.
 */
export function parseRegAFinancialStatements(html: string): RegAStatement[] {
  const $ = cheerio.load(html);
  // Audit status is a property of the REPORT, not of one table. A 1-SA states
  // it once — in a caption, or on the balance sheet only — and every statement
  // in the filing is equally unaudited. Reading it per table marked the balance
  // sheet unaudited and its own cash-flow statement audited.
  const documentUnaudited = /\bunaudited\b/i.test($.root().text());
  const best = new Map<RegAStatementKind, RegAStatement>();

  $("table").each((_i, table) => {
    const $table = $(table);
    const tableText = cellText($table.text());
    const kind = classify(tableText);
    if (kind === null) return;

    const rows: string[][] = [];
    $table.find("tr").each((_j, tr) => {
      const cells: string[] = [];
      $(tr)
        .find("td,th")
        .each((_k, td) => {
          cells.push(cellText($(td).text()));
        });
      rows.push(cells);
    });

    const { columns, periods } = readHeader(rows);
    const dataRows: RegAStatementRow[] = [];

    for (const cells of rows) {
      const labelIndex = cells.findIndex((c) => c !== "");
      if (labelIndex === -1) continue;
      const label = cells[labelIndex];
      // A period heading is not a line item, in any of the three shapes a filer
      // writes one: a full date, a bare year, or the month-and-day half of a
      // header split across two rows.
      //
      // Skipping only the full-date shape let the OTHER two through as data.
      // `['', '', '2019', '', '', '2018', '']` was read as the line item "2019"
      // with the value 2018 — the heading re-entering as a row beneath itself.
      // 654 month-day labels and 10,356 bare-year labels reached storage that
      // way, across 3,148 of 5,695 filings.
      if (
        label === "" ||
        PERIOD.test(label) ||
        BARE_YEAR.test(label) ||
        MONTH_DAY.test(label) ||
        SECTION_HEADING.test(label)
      ) {
        continue;
      }

      // Values come only from cells AFTER the label. A label routinely contains
      // digits — "Common Stock (125,000,000 and 35,146,765 ... shares)" — and
      // scanning the whole row would read the authorised share count as the
      // first period's figure.
      const values = readRowValues(cells.slice(labelIndex + 1));
      if (values.length === 0) continue;

      dataRows.push({
        label,
        // Pad rather than truncate: a row may report fewer columns than the
        // header declares (a line item introduced this period), and dropping it
        // loses a real disclosure.
        values: columns.length > 0 ? padTo(values, columns.length) : values,
      });
    }

    if (dataRows.length === 0) return;

    const statement: RegAStatement = {
      kind,
      columns,
      periods,
      rows: dataRows,
      unaudited: documentUnaudited,
    };
    const existing = best.get(kind);
    if (existing === undefined || statement.rows.length > existing.rows.length) {
      best.set(kind, statement);
    }
  });

  return REGA_STATEMENT_KINDS.map((k) => best.get(k)).filter(
    (s): s is RegAStatement => s !== undefined
  );
}

function padTo(values: number[], length: number): (number | null)[] {
  const out: (number | null)[] = values.slice(0, length);
  while (out.length < length) out.push(null);
  return out;
}
